### ISSUE TITLE
chevron-up in 4.1.1

### ISSUE THREAD

**Issue by jacargentina** [primer/octicons#101]
In 3.5.0 i swear this looked just right (proportonal).
In 4.1.1 now it looks non proportional.

![captura de pantalla de 2016-06-16 14-20-16](https://cloud.githubusercontent.com/assets/517228/16126261/aa2e4bb4-33f7-11e6-92d1-9534f0d8f8fb.png)

Screenshot from  http://smarterp.nexion.com.ar right bottom button to "go up"

Any advice? Is it a "breaking change"? How do i fix it?

**Comment by jonrohan** [comment]
It's not idea, but I would recommend setting a width on the chevron octicon `width: 62px;` would do it.

**Comment by jacargentina** [comment]
So, it is a braking change, right ?

**Comment by jonrohan** [comment]
Yes `4.x.x` is a breaking change. We follow Semantic Versioning http://semver.org so any change to the first  number signals a breaking change.
