### ISSUE TITLE
Cannot use octicons installed via npm

### ISSUE THREAD

**Issue by minamorl** [primer/octicons#102]
I installed octicons by `npm install --save octicons`, as instructed. But after importing `@import "octicons/index.scss";`, this provides only:
```
.octicon {
  display: inline-block;
  vertical-align: text-top;
  fill: currentColor; }
```
I figured out `build/font/octicons.css` is a correct file. Is there proper way to use this?

**Comment by minamorl** [comment]
Solved. Adding below to webpack config:
```
 { test: /\.(png|woff|woff2|eot|ttf|svg)/, loader: 'url-loader?limit=100000' }
```
and then simply import `@import "../node_modules/octicons/build/font/octicons.css"`.
I think it should be noted if `octicons/build/font/octicons.css` is the right path.

**Comment by dinever** [comment]
Hi @minamorl,

Actually GitHub is now using SVG-based icons:

https://github.com/blog/2112-delivering-octicons-with-svg

So the file `index.scss` should only be used with SVG icons now. As you have found, `build/font/octicons.css` or `build/font/_octicons.scss` is the right file if you prefer font-based icons.

**Comment by aaronshekey** [comment]
Thanks for clarifying, @dinever. I'm going to close this out. I'll make a note to improve our Readme :v:
