### ISSUE TITLE
Is it intentional that octicons.min.css is larger than octicons.css?

### ISSUE THREAD

**Issue by shurcooL** [primer/octicons#105]
The .min.css file is minified, and contains no insignificant whitespace or comments.

However, it does contain an inlined (as base64 data) sourceMappingURL comment, which adds significantly to its size.

I can't be sure if this is on purpose or an unintended bug.

https://github.com/primer/octicons/blob/master/build/font/octicons.css - 8.93 KB
https://github.com/primer/octicons/blob/master/build/font/octicons.min.css - 26.7 KB

**Comment by aaronshekey** [comment]
heh, definitely shouldn't be a larger file. @jonrohan, what's with the source mapping comment?

**Comment by jonrohan** [comment]
It's a bug in the compile system.
