### ISSUE TITLE
Thinner icons are no longer horizontally centered in parent container.

### ISSUE THREAD

**Issue by shurcooL** [primer/octicons#107]
This looks like a bug/regression to me, but it's possible I'm doing something wrong. Consider the difference in this minimum reproduce sample:

#### v3.5.0

```HTML
<!DOCTYPE html>
<html lang="en">
	<head>
		<link href="https://rawgit.com/primer/octicons/v3.5.0/octicons/octicons.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div style="display: inline-block; border: 1px solid black;"><span class="octicon octicon-primitive-dot"></span></div>
	</body>
</html>
```

http://instantshare.virtivia.com:27080/pstag10s3f1q.html

![image](https://cloud.githubusercontent.com/assets/1924134/16542863/ed76af54-406f-11e6-91fe-57fa46acbe8f.png)

#### v4.2.0

```HTML
<!DOCTYPE html>
<html lang="en">
	<head>
		<link href="https://rawgit.com/primer/octicons/v4.2.0/build/font/octicons.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div style="display: inline-block; border: 1px solid black;"><span class="octicon octicon-primitive-dot"></span></div>
	</body>
</html>
```

http://instantshare.virtivia.com:27080/dghwesixd1u.html

![image](https://cloud.githubusercontent.com/assets/1924134/16542855/a43ce704-406f-11e6-916a-0e08ceed2a53.png)

Is that intended? If so, how can one center the icon horizontally in parent container?

**Comment by aaronshekey** [comment]
I think this is indeed a regression. If the SVG source is smaller than 16px, the character should also be shorter. 🤔 

We don't use the font-based Octicons anymore on GitHub, so it's easy to miss.

**Comment by shurcooL** [comment]
> We don't use the font-based Octicons anymore on GitHub, so it's easy to miss.

Yeah, I noticed that when I tried to check how it wasn't a problem there. 😄 

I'm curious, what's the reason you switched to svg? Is it technically superior in some ways? If so, I'd probably rather switch too.

**Comment by shurcooL** [comment]
Meta question, I couldn't help but notice those two emojis were rendered in different sizes... Is on purpose?

> 😄
> 🤔

**Comment by aaronshekey** [comment]
> What's the reason you switched to svg?

https://github.com/blog/2112-delivering-octicons-with-svg

> I couldn't help but notice those two emojis were rendered in different sizes

Ask Apple. It's their implementation.

**Comment by shurcooL** [comment]
> Ask Apple. It's their implementation

It doesn't happen without the wrapping though. Look at http://instantshare.virtivia.com:27080/1h79ca5e79350.html, they're rendered in the same size:

![image](https://cloud.githubusercontent.com/assets/1924134/16543232/9cee2cdc-407f-11e6-89d4-bd1becca37eb.png)

> though we wrap the former in a class for fallback purposes. The thinking emoji is new enough that we don't have a fallback.

I think it's exactly because of of the wrapping that it happens. The `g-emoji` class sets `font-size` to `18px`. If you disable that, it makes the two emoji appear same size:

![image](https://cloud.githubusercontent.com/assets/1924134/16543227/7af7eafa-407f-11e6-98a2-b5d988a5f3cc.png)

Sorry about off-topic...

**Comment by aaronshekey** [comment]
`¯\_(ツ)_/¯`

**Comment by aaronshekey** [comment]
I got a chance to poke around at this. We're using [grunt-webfont](https://github.com/sapegin/grunt-webfont) to build our font-based Octicons. It uses font forge as its library, and, unfortunately, it doesn't support thinner glyphs. This functionality can likely be built into `grunt-webfont`, but right now only [this issue](https://github.com/sapegin/grunt-webfont/issues/186) is open. No Pull Requests have been opened yet. Switching to the node library looks terrible, and it looks like it isn't officially supported.

Our font-based implementation of Octicons is basically a nice-to-have at this point. I expect that by version 5 of Octicons, we'll be dropping font support altogether. 

There's really no reason why you couldn't just stay on 3.5 if you really needed the webfont version, right? All of the improvements in recent versions are on the SVG side of things.

**Comment by shurcooL** [comment]
Sounds good to me. My only suggestion would then be to mark webfont as deprecated and note this known issue, but it looks like you have made a PR for that already.

Thanks for looking into it and explaining what's going on!

**Comment by ntkme** [comment]
I have a project that uses font-based Octicons. My solution to this issue was to hard code icon width in em unit. The [stylesheet containing all width](https://github.com/ntkme/github-buttons/blob/master/assets/css/octicons/sizes.css ) was [generated](https://github.com/ntkme/github-buttons/blob/master/src/octicons/sizes.coffee) with Octicons.

With `display: inline-block;`, all the Octicons would display in the correct size. Although it brings a little bit overhead on the css size (~2KB), it will prevent the tiny layout change due to FOUT.
