### ISSUE TITLE
Deprecate font-based Octicons

### ISSUE THREAD

**Issue by aaronshekey** [primer/octicons#108]
It's a lot of work to support the font-based Octicons. Doing so in `4.0` has introduced some regressions #107. We also rely very heavily on `grunt-webfont`, which isn't the most active project out there. We won't be able to realistically dog food the font version since `github.com` has since switched to SVG.

I think we should consider deprecating font-based Octicons.

Thoughts @jonrohan?

**Comment by jonrohan** [comment]
I can't think of any of our own properties that still use the webfont. I'd be down for deprecating it. Maybe `5.0`?

**Comment by brillout** [comment]
A note about that in the readme and release notes would be convenient.
