### ISSUE TITLE
Using octicons

### ISSUE THREAD

**Issue by CrazyPython** [primer/octicons#123]
Octicon install is overly complicated. I have one question:

What do I put in my HTML file?

We don't need node, ruby, or jekyll. I just want to know what to add to my HTML file. Give an example. One we can copy-paste and quickly fit into our existing code.

**Comment by shurcooL** [comment]
There are pre-built octicons available for download at https://octicons.github.com/. Does that help you?

**Comment by mrkkrp** [comment]
Is it possible to insert `sprite.octicons.svg` into HTML without inserting it verbatim? Maybe somethnig using `<object ...>` or similar? Now that there are no fonts, it is not trivial to make it work, I have to say.

**Comment by shurcooL** [comment]
> Now that there are no fonts, it is not trivial to make it work, I have to say.

Yeah, SVG icons require having a little helper code, but then they're super easy to use. It looks like GitHub mention a rails and jekyll helpers:

```
<!-- svg rails helper -->
<%= octicon "alert" %>

<!-- svg jekyll helper -->
{% octicon alert %}
```

If you happen to use [Go](https://golang.org) like me, you can use this Go helper convenience package that returns Octicons SVG as `*html.Node`s for easy rendering with [`html.Render`](https://godoc.org/golang.org/x/net/html#Render).

[https://godoc.org/github.com/shurcooL/octiconssvg](https://godoc.org/github.com/shurcooL/octiconssvg#example-package)

**Comment by mrkkrp** [comment]
I happen to use Haskell :-D OK, it looks like I have no choice but to read the file every time and interpolate… @shurcooL  thanks for your answers.

**Comment by CrazyPython** [comment]
@shurcooL @mrkkrp I don't use rails or jekyll. I just want to embed them like a unicode character, same size as the surrounding text.

**Comment by shurcooL** [comment]
> What do I put in my HTML file?

> Really what I need to know is what font to use.

@CrazyPython, the currently released version of Octicons, v4.3.0 as of this writing, still supports font icons. You can download a pre-built version from https://octicons.github.com/.

Extract the zip, then look for the pre-built .css file at `octicons-4.3.0/build/font/octicons.css` or `octicons-4.3.0/build/font/octicons.min.css`.

Include that CSS in your HTML, and use spans such as `<span class="octicon octicon-alert"></span>` which are documented at https://octicons.github.com/icon/alert/. Does that make sense?

**Comment by CrazyPython** [comment]
@shurcooL Yes. Thank you. 👌  Should be in readme though.

**Comment by shurcooL** [comment]
There is a small section on usage in README at https://github.com/primer/octicons#usage. Perhaps it needs to be improved?

**Comment by CrazyPython** [comment]
@shurcooL Yes. Very confusing, it should be easy and simple, like most things GitHub.

**Comment by shurcooL** [comment]
I'm not sure if the maintainers of this library would want to resolve this documentation issue themselves, or if they'd want a PR. You're welcome to give it a try if you want, there's nothing in [CONTRIBUTING.md](https://github.com/primer/octicons/blob/master/.github/CONTRIBUTING.md) that says documentation PRs are unwelcome.

Otherwise, I'll let them take it from here.

**Comment by mrkkrp** [comment]
Hm, even when I insert the sprite sheet verbatim, icons are not shown. Are `octicon octicon-*` classes enough to show them? Or should I use `<use xlink:href="#alert" /></svg>` or something as in the demo? If yes, I would rather use latest font files and give up on following future releases of the project or switch to something more reasonable.

**Comment by CrazyPython** [comment]
@shurcooL hm, that way gives a square. This is inside a third-party website (I'm developing a chrome extension that adds on to webpages).

**Comment by jonrohan** [comment]
You should use the `<use` tag. In https://github.com/primer/octicons/pull/121 I created a demo that gets built for the `/build/` folder. This is in the unreleased HEAD in master, which will become 5.0.0 To view this, clone the repository and run [build instructions](https://github.com/primer/octicons#building-octicons)

If you're still having trouble, here's a gist with the same html https://gist.github.com/jonrohan/31d7f4ee50e8ff544ba46b6089345fa7

**Comment by CrazyPython** [comment]
@jonrohan conflicting advice here. Just want the octicon to be the same size as the surrounding text. No 16 or 32 px.

**Comment by jonrohan** [comment]
The browser treats the svg similarly to how it treats img tags. What you can do is remove the `height` and `width` attributes from the svg `<use>` and then apply with CSS a `height: 1em;` which will be equal to the font size. Here's a demo http://codepen.io/jonrohan/pen/jrAJza

**Comment by CrazyPython** [comment]
@jonrohan I see. Again, not documented in README. Octicons look cool and their usage guide should be too.

**Comment by CrazyPython** [comment]
@jonrohan Let's say I want to use one octicon only, say clippy. What is the minimum required HTML to do that? The codepen and the gist seem to have a lot of unneeded things. Really, I'm asking what to put in my `<head>`.

**Comment by viharm** [comment]
Surely CSS files should be available for download, right?

**Comment by Sdlion** [comment]
Got in the same situation: wanting to simply insert one (or several, but not all) octicon on a template.
Combining the `svg` tag suggestion on the spritesheet demo with the `image` tag suggested [here](http://edutechwiki.unige.ch/en/Using_SVG_with_HTML5_tutorial) did the trick.

```
<svg version="1.1" width="32" height="32" viewBox="0 0 16 16" class="octicon octicon-x" aria-hidden="true">
    <image xlink:href="/css/octicons/svg/x.svg" />
</svg>
```
