### ISSUE TITLE
Codepoints listing

### ISSUE THREAD

**Issue by masaeedu** [primer/octicons#128]
This might just be me misunderstanding how github works, but I can't find the `codepoints.json` file you used to have in an earlier commit: https://github.com/primer/octicons/pull/100/files.

This is useful to have because it makes it less confusing to debug font issues and reason about what codepoints to include when consuming the library (e.g. see ryanoasis/nerd-fonts/issues/87).

**Comment by jonrohan** [comment]
The codepoints.json file is in the latest release https://github.com/primer/octicons/blob/v4.3.0/lib/font/codepoints.json

But as of 5.0.0 https://github.com/primer/octicons/issues/108 we're going to be deprecating support for the font file. On master right now is the unreleased 5.0 https://github.com/primer/octicons/blob/master/CHANGELOG.md#500

**Comment by shurcooL** [comment]
Was this issue about codepoints listing (which is font-specific) or about keywords listing (which relates to Octicons in general, not font or SVG-specific)?

Based on the linked PR, which added "Keywords.json file that has an index of all octicons with alias names, I thought it was about `keywords.json`.

It looks like `keywords.json` is still there, it was just renamed to `data.json`:

https://github.com/primer/octicons/blob/master/lib/data.json
