### ISSUE TITLE
Missing v4.4.0 on GitHub

### ISSUE THREAD

**Issue by PeterDaveHello** [primer/octicons#131]
Hello, I just found that v4.4.0 is on npm but not GitHub, could you please also tag it on GitHub? So that we can also have the latest version on CDNJS: https://cdnjs.com/libraries/octicons which is use your GitHub repository as source of auto-update, thanks!

**Comment by jonrohan** [comment]
Thanks for the issue, forgot to `git push --tags`

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/octicons v4.4.0 is now on CDNJS! @jonrohan can we also add the cdn info in readme? Thanks.
