### ISSUE TITLE
Unable to inherit color

### ISSUE THREAD

**Issue by tnguyen14** [primer/octicons#133]
I am using the SVG like so:

```
					<svg class="octicon">
						<use xlink:href="sprite.octicons.svg#file-text">
					</svg>
```

With the styles for `.octicon` as suggested (`fill: currentColor`)

The icons are not inheriting the color of the parent element however. What I've found is that for certain icons, such as `file-text`, the color will cascade. However, for many other icons (such as `trashcan`), the color stays black.

Looking at the source code of these icons, they look quite different. Specifically, the one for `trashcan` has more grouping elements etc.

Is it possible to change the color of the icons when using it externally like what I'm doing?

**Comment by broccolini** [comment]
Thanks for the feedback. We're doing some work on updating our icons and we'll take a look at this issue. cc @jonrohan @sophshep

**Comment by jonrohan** [comment]
I would suggest looking at the spritesheet demo https://unpkg.com/octicons@5.0.0/build/sprite.octicons-demo.html and making sure you have everything similarly setup. I'm setting the color on the body and getting color inheritance

![image](https://cloud.githubusercontent.com/assets/54012/19822271/aaebf5f4-9d30-11e6-9df1-537963fcd724.png)

**Comment by tnguyen14** [comment]
@jonrohan Thanks. I was on v4.4.x. Upgrading to v5 and it's working now.

**Comment by tnguyen14** [comment]
I also set `fill: currentColor` property on the `svg` element. Otherwise, it does not inherit `color` of the parent element. I don't see that in your demo setup, so not sure how it works there.
