### ISSUE TITLE
If using SVGs on website do I have to reference the license in e.g. legal notice or similar?

### ISSUE THREAD

**Issue by AndreasA** [primer/octicons#136]
If I want to use the SVG icons on a website, do I have to but the SIL OFL 1.1 license somewhere on the website like a "Legal Notice" page, so users can check for it?
Or is it enough if I add the information as HTML comment or can I just use them or ..?

Because I don't see any license information in the SVG files themselves.

If any notice is required anywhere what exactly needs to be put there?
Something like:
This website uses octicons SVGs which are licensed under SIL OFL 1.1 (http://scripts.sil.org/OFL)
?

**Comment by jonrohan** [comment]
Thanks for the question @AndreasA, I'm asking our legal experts for help in answering. Hold tight

**Comment by jonrohan** [comment]
Upon further research, we don't require you to add any notices to use the SVG icons on a website - you can just use them. Thanks

**Comment by AndreasA** [comment]
Thanks
