### ISSUE TITLE
Spritesheet has size

### ISSUE THREAD

**Issue by Martii** [primer/octicons#141]
Re: 
* https://github.com/primer/octicons/blob/6b208feb8d505f6bf1f040de7a9e950d5d459285/README.md#spritesheet
* https://css-tricks.com/svg-sprites-use-better-icon-fonts/#SVG *(under "Inject that SVG at the top of the document")*

The suggestion on that page says to inject the sprite sheet svg into the body of the html document. However it has width and height on some browsers since the "definitions" aren't set to initial width and height values of zero.

I read about the "pseudo-requirement" of it being the first item in the `body` tag but if we use CSS to control via `display` or `width`/`height` that ceases to be the first tag under body.

I'll twiddle with it some more but I was wondering if there is a recommended pattern so that it doesn't have width/height that won't contradict with any current 1.1 specification and/or interpretation.

Thanks so much for some advisement.

**Comment by jonrohan** [comment]
In the sprite sheet demo https://unpkg.com/octicons@5.0.0/build/sprite.octicons-demo.html, we set `style="width:0;height:0;visibility:hidden;"` on the `<svg` tag to hide it from the page.

**Comment by Martii** [comment]
@jonrohan 
When I'm through fixing some passports I'll put in a reduced test case that definitely doesn't show the icons... something on your server code appears to be loading the sprite but I don't see the reference to it... when it's added per that documentation is the only time my test showed up...anyhow... will be back later for this. Thanks.
