### ISSUE TITLE
ERB templating shipped on the live site

### ISSUE THREAD

**Issue by IonicaBizau** [primer/octicons#149]
![image](https://cloud.githubusercontent.com/assets/2864371/20710834/121406ae-b645-11e6-8001-6d4fe340d479.png)

**Comment by jonrohan** [comment]
That's on purpose for easy copy paste. For use with the https://github.com/primer/octicons_helper and https://github.com/primer/jekyll-octicons

**Comment by IonicaBizau** [comment]
@jonrohan Ah, you're right! I didn't read the comments. :joy:

But still, it would be nice to show there the `<span class="..."></span>` way too. I usually use it in plain HTML.
