### ISSUE TITLE
Octicons are blurry

### ISSUE THREAD

**Issue by flying-sheep** [primer/octicons#151]
On GitHub, you use octicons e.g. in the repo and Gist buttons (watch/delete/fork/star)

However, text isn’t aligned to the pixel raster. Therefore inline SVG elements are shifted by subpixels, making them look blurry (Firefox on top, Chrome on the bottom):

![blurry-svg](https://cloud.githubusercontent.com/assets/291575/21232948/bbe3f3a6-c2ed-11e6-82df-a910a366eb75.png)

There is a [feature request](https://bugzilla.mozilla.org/show_bug.cgi?id=1003763) for Firefox to allow circumventing this, but **Firefox does nothing wrong here**: It isn’t specified that SVG elements have to be aligned to the pixel raster, so arguably *everyone else* could be wrong.

**Comment by simurai** [comment]
Note that you might need to slowly resize the window to see the blurry-ness:

![blurry](https://cloud.githubusercontent.com/assets/378023/21284078/17f9fc96-c454-11e6-9d9a-7d1c05dd1507.gif)

Tried a few things like `-moz-osx-font-smoothing: grayscale` or `image-rendering: -moz-crisp-edges` but that has no effect. 😭  The only fix I found is to use `position: absolute` for the svg icon (and add some extra left padding on the button). But that complicates things more, so not sure.

**Comment by flying-sheep** [comment]
float works neither, since it destroys the vertical alignment.

`display: flex` works: http://codepen.io/flying-sheep/pen/GNPXjX

for this pen i added two copies, one with and one without the `.new-svg` class.

at the top of the CSS there’s two blocks affecting one of the columns. one with the old and one with the new style.

**Comment by jonrohan** [comment]
This is good to know, but at this point I don't know what we can do to fix it. Adding `position, display, or float` to our icons or buttons is not an option. I'll label this a bug and hope that a solution pops up from firefox one day. :sob:

**Comment by LMLB** [comment]
Applying a `transform` (such as `scale(1)` or `translate(0,0)`) to `svg` elements makes Firefox snap them to pixels.
