### ISSUE TITLE
Outdated contributing guidelines

### ISSUE THREAD

**Issue by shgysk8zer0** [primer/octicons#158]
`/.github/CONTRIBUTING.md` refers to `/octicons/svg` and mentions being "GitHub's icon font," even though fonts were deprecated in #108. 

Also, license in `package.json` includes "OFL". Not sure if this still applies or if it needs to remain due to there being fonts in previous versions.

I don't know if the SVGs are still generated by an automated process. From what I can tell, `/lib/octicons-master.sketch` is the original file that is used to generate all `/lib/svg/*.svg` (running Linux and have no access to Sketch).

Do you not accept pull requests or issues relating to changes in icons? If someone did want to contribute by adding an icon or changing an existing one, would you accept a pull request involving just an SVG, or would you require changes in Sketch? If you accept changes to SVGs, do you require the `<?xml version="1.0" encoding="UTF-8"?>` and all attributes on `<svg>`?

**Comment by sophshep** [comment]
Thank you for bringing the outdated contributing guidelines to our attention, @shgysk8zer0! I have updated them to no longer reference the font.

I believe the OFL license still applies, as it is written for "fonts and related software" and our Octicons should fall into the latter bucket.

> Do you not accept pull requests or issues relating to changes in icons? 

At this time, we are not accepting contributions. I will work with our team to update `CONTRIBUTING.md` to include this as well.
