### ISSUE TITLE
Two Ellipse Icons - Duplicate

### ISSUE THREAD

**Issue by GladLock** [primer/octicons#159]
I noticed you have two ellipse icons of the exact same thing, I assume it's just because of a misspelling:

.octicon-ellipsis 
.octicon-ellipses

**Comment by shurcooL** [comment]
They do look identical.

- https://octicons.github.com/icon/ellipsis/
- https://octicons.github.com/icon/ellipses/

**Comment by GladLock** [comment]
Is one meant to be vertical and the other horizontal?

**Comment by djch** [comment]
In case anyone's confused about the grammar: 'ellipsis' is singular and 'ellipses' is plural, so 'ellipsis' would be more accurate I imagine.

**Comment by dkfiresky** [comment]
I think it's just an alias for `.octicon-ellipsis`

**Comment by cmwinters** [comment]
Not sure what the origin of this duplicate is, but thanks for pointing it out!

**Comment by jonrohan** [comment]
Yup, this was some kinda dupe mistake. Got a pull to delete one.
