### ISSUE TITLE
commercial use?

### ISSUE THREAD

**Issue by ClaudioCarmeli** [primer/octicons#161]
I have read the  SIL OFL 1.1 documents but I am still not sure on whether it is possible to use the vector files (other than the Github logos) for commercial purposes or not.

**Comment by sophshep** [comment]
Hi @ClaudioCarmeli. Yes, you can use these icons for commercial use. https://choosealicense.com/licenses/ofl-1.1/ has it annotated as allowing commercial use, but if you want a legal opinion it would be best to consult your own attorney.
