### ISSUE TITLE
Octicons in @angular/cli

### ISSUE THREAD

**Issue by dolanmiu** [primer/octicons#162]
Can someone direct me in some documentation or basic guide for it to work with an Angular project scaffolded with `@angular/cli`?

I have added:

```json
      "styles": [
        "../node_modules/octicons/build/octicons.css",
        "global-styles/index.scss"
      ],
```

but it seems like it doesnt do anything

**Comment by thadamski** [comment]
I'm also struggling with adding octicions to my project. @dolanmiu, have you figured out a technique since creating this issue?

**Comment by dolanmiu** [comment]
Nope, havent figured it out, but it seems `../node_modules/octicons/build/octicons.css` doesnt have anything icon related inside.

**Comment by jonrohan** [comment]
The `octicons.css` file is basic styling for the SVG icons. You'll still need to put the SVG code into your project. We have a couple of options; ([Node API](https://github.com/primer/octicons#node), [sprite sheet](https://github.com/primer/octicons#spritesheet)). Also, some [other platform delivery methods](https://github.com/primer?utf8=%E2%9C%93&q=octicons&type=&language=) which you could model an Angular solution after. I'm not an Angular expert, but will gladly answer any questions I can.

**Comment by robisim74** [comment]
For anyone interested, the following configuration for Angular CLI works:

Add to `.angular-cli.json`:
```
"styles": [
        ...
        "../node_modules/octicons/build/build.css"
      ],
```
Import `octicons` into the component:

`import * as octicons from 'octicons';`

At this point it is possible to use it. A simple example can be the following:

```
    star: any;

    constructor() {
        this.star = octicons.star.path.match(/d="(.*)"/)[1];
    }
```

And in the template:
```
                <svg fill="black" height="24" width="24" class="octicon">
                        <path [attr.d]="star" />
                </svg>
```

For a more structured solution, a specific component or directive should be built.

**Comment by mjluck** [comment]
> EDITED
> 
> At this point it is possible to use it in several ways. For example, building a directive:
> 
> import { Directive, Input, OnInit, ElementRef, Renderer2 } from '@angular/core';
> 
> import * as octicons from 'octicons';
> 
> @Directive({
>     selector: '[octicon]'
> })
> export class OcticonDirective implements OnInit {
> 
>     @Input() octicon: string;
>     @Input() color: string;
>     @Input() width: number;
> 
>     constructor(private elementRef: ElementRef, private renderer: Renderer2) { }
> 
>     ngOnInit(): void {
>         const el: HTMLElement = this.elementRef.nativeElement;
>         el.innerHTML = octicons[this.octicon].toSVG();
> 
>         const icon: Node = el.firstChild;
>         if (this.color) {
>             this.renderer.setStyle(icon, 'color', this.color)
>         }
>         if (this.width) {
>             this.renderer.setStyle(icon, 'width', this.width);
>             this.renderer.setStyle(icon, 'height', '100%');
>         }
>     }
> 
> }
> Usage:
> 
> <span octicon="mark-github" color="red" width="32"></span>

I found this very useful, but when I tried to implement it directly I found the color would not change.  Had to change the if statement for color to **this.renderer.setStyle(icon, 'fill', this.color);** 

After that the color filled correctly, hopefullly this will help anyone having the same issue and is new like me :D.

**Comment by eddied2702** [comment]
This example is great and it worked for me. However how do I use the typical syntax instead of this custom version. 

So instead of using 
<span octicon="gear" color="red" width="32"></span>

I want to use the typical way 
<span class="octicon octicon-gear"></span>

**Comment by qaisjp** [comment]
So to combine both @robisim74 and @mjluck's comments:

1. Generate a directive: `ng generate directive octicon`
2. Open `octicon.directive.ts`
3. Add the following imports (there should already be an `import { Directive } from '@angular/core';`)

    ```typescript
    import { Directive, Input, OnInit, ElementRef, Renderer2 } from '@angular/core';
    import * as octicons from '@primer/octicons';
    ```
    Note that you now need to import from `@primer/octicons`, not just `octicons`. I am not sure if [this page](https://github.com/primer/octicons/tree/master/lib/octicons_node) needs to be updated.
4. Update the decorator from `selector: '[appOcticon]'` to `selector: '[octicon]'`

    ```typescript
    @Directive({
      selector: '[octicon]'
    })
    ```
5. Make sure `class OcticonDirective implements OnInit` (`implements OnInit` is not a default when generating a directive)
6. Copy `class OcticonDirective` content from the final `octicon.directive.ts` file below.

**octicon.directive.ts**
```ts
import { Directive, Input, OnInit, ElementRef, Renderer2 } from '@angular/core';

import * as octicons from '@primer/octicons';

@Directive({
  selector: '[octicon]'
})
export class OcticonDirective implements OnInit {

  @Input() octicon: string;
  @Input() color: string;
  @Input() width: number;

  constructor(private elementRef: ElementRef, private renderer: Renderer2) { }

  ngOnInit(): void {
    const el: HTMLElement = this.elementRef.nativeElement;
    el.innerHTML = octicons[this.octicon].toSVG();

    const icon: Node = el.firstChild;
    if (this.color) {
      this.renderer.setStyle(icon, 'fill', this.color)
    }
    if (this.width) {
      this.renderer.setStyle(icon, 'width', this.width);
      this.renderer.setStyle(icon, 'height', '100%');
    }
  }

}
```

Now you can just use the `octicon` attribute wherever you like. Examples:
- `<i octicon="search"></i>`
- `<span octicon="mark-github" color="red" width="32"></span>`

**Comment by qaisjp** [comment]
An addition I've made for my own project is this:

```diff
diff --git a/website/src/app/octicon.directive.ts b/website/src/app/octicon.directive.ts
index 2e387ed..3f14aa9 100644
--- a/website/src/app/octicon.directive.ts
+++ b/website/src/app/octicon.directive.ts
@@ -16,6 +16,7 @@ export class OcticonDirective implements OnInit {
   ngOnInit(): void {
     const el: HTMLElement = this.elementRef.nativeElement;
     el.innerHTML = octicons[this.octicon].toSVG();
+    el.classList.add("octicon-parent");

     const icon: Node = el.firstChild;
     if (this.color) {
```

And then adding the following to styles.css:

```css
.octicon-parent {
  display: flex;
  align-items: center;
}
```

**Comment by angela-1** [comment]
My solution is use `innerHTML` with `bypassSecurityTrustHtml` to get svg.
Can recive 'small', 'large', number icon size. 
(@primer/octicons 10.0.0 has 16 and 24 px size, 16 is small, 24 is large)


**Usage**
`<app-icon name="mark-github"></app-icon>`

**Code**
icon.component.html
`<span [innerHTML]="svg | bypasshtml"></span>
`

icon.component.ts
```
import { Component, OnInit, Input } from '@angular/core';
import octicons from '@primer/octicons';

enum IconSize {
  Small = 16,
  Large = 24
}

@Component({
  selector: 'app-icon',
  templateUrl: './icon.component.html',
  styleUrls: ['./icon.component.scss']
})
export class IconComponent implements OnInit {
  /**
   * icon name
   */
  @Input() name: string;

  /**
   * icon size
   */
  @Input() size: 'small' | 'large' | number = IconSize.Small;

  /**
   * generate svg
   */
  svg: string;

  ngOnInit(): void {
    this.svg = octicons[this.name]?.toSVG({ height: this.getSize(this.size) });
  }

  /**
   * get icon size in number
   * @param size icon size
   */
  getSize(size: string | number): number {
    let sizeNumber = IconSize.Small;
    if (typeof size === 'string') {
      switch (size) {
        case 'small':
          sizeNumber = IconSize.Small;
          break;
        case 'large':
          sizeNumber = IconSize.Large;
          break;
        default:
          sizeNumber = IconSize.Small;
          break;
      }
    } else {
      sizeNumber = size;
    }
    return sizeNumber;
  }
}
```

bypasshtml.pipe.ts
```
import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Pipe({
  name: 'bypasshtml'
})
export class BypasshtmlPipe implements PipeTransform {
  constructor(private domSanitizer: DomSanitizer) {}

  transform(html: string, ...args: unknown[]): unknown {
    return this.domSanitizer.bypassSecurityTrustHtml(html);
  }
}
```
