### ISSUE TITLE
Where can I find the Sass file to import?

### ISSUE THREAD

**Issue by derwaldgeist** [primer/octicons#166]
I was using an earlier version via bower so far and just switched to npm. But after installing this package, I could not find the scss file to import any more. Seems as if this package switched to a JS-based syntax? In the issues I can see references to Sass, but not in the package anymore. Is there still a Sass version somewhere?

**Comment by jonrohan** [comment]
Since version 5.0, we deprecated the font-based icons and switched to SVG. Read about these changes here https://github.com/blog/2112-delivering-octicons-with-svg

Since then we no longer include Sass files
