### ISSUE TITLE
How can I render a circle (dot) icon?

### ISSUE THREAD

**Issue by ifyouseewendy** [primer/octicons#167]
Hi, thanks for making the repo. It's awesome. 

I'm looking for a normal size dot icon, which I could only find the `primitive-dot` class. Is it the right way to decorate the class to make it?

Thanks

**Comment by shurcooL** [comment]
There are many ways to make a circle, there's no single one right way.

You could define your own SVG element that creates a circle of the right size, that's likely the easiest way.

**Comment by ifyouseewendy** [comment]
I created a circle using CSS properties. Thanks for the help!
