### ISSUE TITLE
octicons.css is basically empty. Drop support of CSS or build error?

### ISSUE THREAD

**Issue by saschal-j5int** [primer/octicons#168]
Hi,

we used to import the octicons.css file in our project and refer to the octicons via the html class attribute. We tried to upgrade from version 3.5 to 5.0.1. Looking in the build/octicons.css file it is basically empty. Previously it contained all the icon declaration. Now it just contains:

```
.octicon {
  display: inline-block;
  vertical-align: text-top;
  fill: currentColor;
}
```
did you guys drop the support for CSS based octicons? 

Thanks

**Comment by saschal-j5int** [comment]
I see in version 4.4.0 you still had a working version with build/font/octicons.css. This file doesn't exist anymore in >= 5.0

**Comment by shurcooL** [comment]
> did you guys drop the support for CSS based octicons?

Yes, font-based Octicons were deprecated in 5.0. See issue #108 and PR #117 that implemented it.

Also see https://github.com/blog/2112-delivering-octicons-with-svg that provides explanation of why SVG icons are superior over font-based ones.

**Comment by saschal-j5int** [comment]
Thanks for letting me know.

**Comment by saschal-j5int** [comment]
Could you please change your readme then to ensure people are aware of this, because it still says:

> For all the usages, we recommend using the CSS located in build/octicons.css. This is some simple CSS to normalize the icons and inherit colors.

thanks.

**Comment by jonrohan** [comment]
The CSS is recommended to give the SVG paths proper height and spacing when used on the page. It's the same CSS we use for the icons here.

**Comment by dalu** [comment]
This is the dumbest thing ever.

**Comment by cowbert** [comment]
@dalu I agree, especially because it's giving a bad look for [people trying to use this with Boostrap](https://github.com/twbs/bootstrap/issues/25527)
