### ISSUE TITLE
Octicon request: Archived repo

### ISSUE THREAD

**Issue by sophshep** [primer/octicons#182]
We need an icon to represent an archived repo. No major rush on it, but if/when we start adding icons again or redesign the system, I wanted to record this.

UI examples and conversation happening here: https://github.com/github/github/pull/80421)

**Comment by broccolini** [comment]
I'll grab this one, it's a good excuse to go through the entire flow (and document it) with the new monorepo.

**Comment by colinkeany** [comment]
Hey, hope it's alright to jump in on this issue, but I spoke with @jonrohan and @broccolini yesterday about also needing an "archive" icon, and we decided I could be the guinea pig for the new octicon contributor flow via Figma. So here we go!

I've added 2 versions of an archive icon in this file. One is based on some of the feedback from [this issue](https://github.com/github/github/pull/80421) linked above, and the other is an alternative I thought could be interesting, and holds up a little better at a smaller scale.

**Link to my draft of the octicons file:** https://www.figma.com/file/taeondve1a0gWuNuEN4RJ3/Octicons-Colin-Adding-Archive-Icon

**Screenshots:**

Archive icon 1
![screen shot 2018-04-05 at 11 46 40 am](https://user-images.githubusercontent.com/4369448/38376647-11e577ca-38c7-11e8-91ac-e0a9bb95386d.png)

Archive icon 2
![screen shot 2018-04-05 at 11 46 44 am](https://user-images.githubusercontent.com/4369448/38376666-1bfa4eb6-38c7-11e8-8f9c-f482753f535d.png)

Smaller
![screen shot 2018-04-05 at 11 39 41 am](https://user-images.githubusercontent.com/4369448/38376684-29cee182-38c7-11e8-9b7a-b13bc9da433b.png)

**In context (issue timeline)**

Icon 1, dark icon on light bg
![screen shot 2018-04-05 at 11 36 20 am](https://user-images.githubusercontent.com/4369448/38376717-4052d742-38c7-11e8-8360-23de395b8036.png)

Icon 1, light icon on dark bg
![screen shot 2018-04-05 at 11 35 30 am](https://user-images.githubusercontent.com/4369448/38376764-5b1bb44a-38c7-11e8-9c38-f80216108baa.png)

Icon 2, dark icon on light bg
![screen shot 2018-04-05 at 11 39 00 am](https://user-images.githubusercontent.com/4369448/38376796-6dc34892-38c7-11e8-93a6-545ed0d41695.png)

Icon 2, light icon on dark bg
![screen shot 2018-04-05 at 11 38 29 am](https://user-images.githubusercontent.com/4369448/38376855-8ca0b0f6-38c7-11e8-8b4a-3211c675b4fc.png)

**Comment by colinkeany** [comment]
Yeah I had similar feelings about how the outlined box icon held up in comparison to the arrow icon.

I'm leaning a little more in the direction of the box icon only for the sake of clarity. I do think the arrow icon has some traction as an "archive" icon, but I don't have examples right now to back that up.

**Comment by colinkeany** [comment]
Bump!

We're making good progress on the project card archival feature and I would love to be able to get an icon sorted out for this so we can start including it in the UI. What can I do to help move this along?

**Comment by colinkeany** [comment]
Some updates based on the discussion at design review:

**Filled in box icon**

![screen shot 2018-04-21 at 10 07 11 am](https://user-images.githubusercontent.com/4369448/39085074-d4cd0812-454b-11e8-867d-9d209e7f06b6.png)
![screen shot 2018-04-21 at 10 07 21 am](https://user-images.githubusercontent.com/4369448/39085075-d7abfc28-454b-11e8-9fb8-de68190107bf.png)
![screen shot 2018-04-21 at 10 04 02 am](https://user-images.githubusercontent.com/4369448/39085058-a9c78746-454b-11e8-8e23-a3e8b5071fb3.png)

**Comment by broccolini** [comment]
@colinkeany I think the original outline box works best and fits with the other icons. `Icon 1 dark on light background` seems like a good combo. Would you be happy moving forward with that? If so, we can help you with adding this to Octicons.

**Comment by colinkeany** [comment]
@broccolini yup that's good with me!
