### ISSUE TITLE
kebab-horizontal and/or kebab-vertical cause Jekyll build failure

### ISSUE THREAD

**Issue by Derjyn** [primer/octicons#193]
What it says on the tin.  I'm going through and testing all the Octicons with Jekyll, and so far those cause build failures.

EDIT, found more, will update and list all found build failure-inducing Octicons:

- kebab-horizontal
- kebab-vertical
- note
- project (really?!)
- pulse
- screen-full
- screen-normal

I may have missed some, but that seems to be it.  Hope it helps.  Is there any sort of working list with all the icons?  I ended up making a text file and adding them all in...

**Comment by jonrohan** [comment]
Can you be more specific on the failure? What is the output of the failure? We have the kebabs working on this jekyll build https://octicons.github.com/icon/kebab-horizontal/
