### ISSUE TITLE
Fix heart icon

### ISSUE THREAD

**Issue by broccolini** [primer/octicons#197]
<img width="970" alt="screenshot 2018-02-23 12 54 52" src="https://user-images.githubusercontent.com/334891/36609361-9c2bb4be-189a-11e8-9a6c-54362e36301b.png">

<img width="1139" alt="screenshot 2018-02-23 12 55 29" src="https://user-images.githubusercontent.com/334891/36609371-a06f9f86-189a-11e8-8f0b-33c212118a6b.png">

🙈

**Comment by sophshep** [comment]
![image](https://user-images.githubusercontent.com/527589/36609871-f8b1e7e6-1893-11e8-88ee-0db9a9452920.png)

![image](https://user-images.githubusercontent.com/527589/36610108-ac3f9272-1894-11e8-9dd2-31af6e33502f.png)

![image](https://user-images.githubusercontent.com/527589/36610053-8ac01f7c-1894-11e8-8212-84341ea53fd8.png)
