### ISSUE TITLE
Question: Should we change the lerna versioning config?

### ISSUE THREAD

**Issue by jonrohan** [primer/octicons#205]
Currently the versioning config in lerna is managed independently. Which lets you give a specific version number for each package in `/lib/`.

It makes sense to me that all people care about is the version of the icons (SVGs). If an icon is updated or added. Those specific versions rely only on the `octicons_node` package. That then becomes weird because the lesser packages like jekyll-octicons don't match even though they have the same icon set.

### What happens if we update jekyll-octicons only and not the icons?

Lerna says in locked mode, https://github.com/lerna/lerna#fixedlocked-mode-default

> When you run lerna publish, if a module has been updated since the last time a release was made, it will be updated to the new version you're releasing. This means that you only publish a new version of a package when you need to.

So I think if we updated jekyll-octicons from 8.0.0 -> 8.0.1 then these changes would happen because of dependency

* Repo version 8.0.0 -> 8.0.1
* jekyll-octicons 8.0.0 -> 8.0.1
* octicons_gem 8.0.0 -> 8.0.1
* octicons_node 8.0.0 -> 8.0.0
* octicons_helper 8.0.0 -> 8.0.0

**Comment by shurcooL** [comment]
Given #208 and #220 have been merged, should this issue be closed now? Or is there more to be done here?

**Comment by jonrohan** [comment]
Yup, thanks!
