### ISSUE TITLE
Why are the fill attribute fixed to black in the svg files included in the zip??

### ISSUE THREAD

**Issue by ruifortes** [primer/octicons#210]
Hi.
I just downloaded the zip from the [official site](https://octicons.github.com) and the included svg files have the "fill" attribute fixed to black.  
I'm using webpack to bundle in all svg files and I have to manually remove the fill attribute from the files in order to control it's color from css.
I'm linking to <symbol> so I cannot even override it with "!important"
What the proper way of using the svg files directly?
Thanks

**Comment by jonrohan** [comment]
Apologies that wasn't updated with the release this week, I've updated it. You should find optimized svg files in `/build/svg/`.

If you're Interested, I'm currently working on an official react component https://github.com/primer/octicons/pull/196 still a work in progress but you can test out the alpha releases https://www.npmjs.com/package/%40github%2Focticons-react
