### ISSUE TITLE
Cannot make new export process work

### ISSUE THREAD

**Issue by cyberalien** [primer/octicons#213]
I want to get SVG files, so I've cloned repository, ran `npm install` and `script/export`

Second command exits with this error:

```slava@dev:/mnt/d/lib/svg/octicons$ ./script/export
ℹ Exporting octicons from https://www.figma.com/file/FP7lqd1V00LUaT5zvdklkkZr/Octicons file
ℹ Getting components from the figma file
✖ Error: Getting getting octicons from figma file
{ RequestError: getaddrinfo ENOTFOUND undefined undefined:443
    at ClientRequest.req.once.err (/mnt/d/lib/svg/octicons/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:255:19)
    at ClientRequest.emit (events.js:160:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  name: 'RequestError',
  code: 'ENOTFOUND',
  host: 'undefined',
  hostname: 'undefined',
  method: 'GET',
  path: '/v1/files/FP7lqd1V00LUaT5zvdklkkZr',
  protocol: 'https:',
  url: 'https://undefined/v1/files/FP7lqd1V00LUaT5zvdklkkZr' }
```

Running it in WSL.

That's the only instruction I found on how to export SVG from https://github.com/primer/octicons/pull/202
Unfortunately I don't see any other documentation that could explain export process.

**Comment by jonrohan** [comment]
Sorry for the confusion. the export script is meant to work with figma api tokens and is intended for our CI to run, not locally. If you have a figma account you can duplicate [the file](https://github.com/primer/octicons/blob/master/package.json#L9) and use/export them. However you don't need to that way.

[<img src="https://user-images.githubusercontent.com/54012/38514516-4793c094-3be6-11e8-9c7f-90fd3e6ddb05.png" width="400"/>](https://octicons.github.com/)

You can download the latest release on https://octicons.github.com/ by clicking the green "Download Octicons" button. This will download a compressed folder of the latest npm release. Unzip the file and look in the `/build/svg` folder. All of the svg files exist there.
