### ISSUE TITLE
How to use ocitcons with sass?

### ISSUE THREAD

**Issue by blachawk** [primer/octicons#218]
Is there anyway we can use your icons in a SASS or SCSS document as background images?  If this is possible, what would be a general guideline for setting up something like this?

Thanks

**Comment by jonrohan** [comment]
We don't currently have this ability, but I could see it as an option. I'm leaving this open.

**Comment by pschfr** [comment]
For what it's worth, I was able to `@import` Octicons in Sass by simply renaming `build.css` to `build.scss`. Perhaps that's worth noting somewhere?
