### ISSUE TITLE
React version onClick

### ISSUE THREAD

**Issue by carstenmuellerlemberg** [primer/octicons#304]
Hello,

I tried the onClick event in the octicons tag, but the function is not called.
Is on Click supported?

<Octicon icon={iconsByName.trashcan} onClick={() => this.callFunc()} />

**Comment by emplums** [comment]
Hey @carstenmuellerlemberg - we don't support `onClick` on Octicons because we're rendering out `svg` elements which don't support click events natively. For accessibility reasons, we recommend wrapping the Octicon in a `<button>` or `<a>` if you'd like to trigger an event onClick
