### ISSUE TITLE
Design file / workflow for Sketch?

### ISSUE THREAD

**Issue by rayshan** [primer/octicons#315]
Hi! Given this ticket: https://github.com/primer/octicons/pull/202, what's the recommended workflow for Sketch users designing with Octicons?

**Comment by yaili** [comment]
Hi. We don't have a Sketch file anymore, but feel free to check our [Figma file](https://www.figma.com/file/FP7lqd1V00LUaT5zvdklkkZr/Octicons?node-id=0%3A1)
