### ISSUE TITLE
Printer logo

### ISSUE THREAD

**Issue by muellerj** [primer/octicons#32]
A printer logo would be a really nice addition. Font Awesome has a pretty decent one: http://fortawesome.github.io/Font-Awesome/icon/print/.

![screen shot 2014-12-16 at 22 47 30](https://cloud.githubusercontent.com/assets/53246/5462573/9508d7a4-8575-11e4-881e-2abffc8d30e0.png)

**Comment by sophshep** [comment]
Hi @muellerj,

Thank you for the request! We're not currently adding new octicons, however we will make a note of this suggestion to revisit next time we make updates.
