### ISSUE TITLE
Wishlist: Allow arbitrary icons sizes

### ISSUE THREAD

**Issue by chrishiestand** [primer/octicons#321]
While the size property seems to fill the common use cases, since these are vector graphics they will easily scale to any size and there are times when users will want a non-standard size.

I'd like to have the icon basically implement `width: 100%` so that it fills the html element it's in. Oddly enough - this is the effect if you enter an invalid size property such as:
```jsx
            <Octicon icon={Globe} size="invalid" />
```

**Comment by colebemis** [comment]
@chrishiestand `size="100%"` should work for you. Here's an example: https://codesandbox.io/s/laughing-field-ugkei?file=/src/App.js
