### ISSUE TITLE
404: not found when clicking download on https://octicons.github.com/

### ISSUE THREAD

**Issue by Doh09** [primer/octicons#325]
Hey,

I get a "404: not found" when clicking download on https://octicons.github.com/

![image](https://user-images.githubusercontent.com/21059484/60183178-0fa28880-9826-11e9-95e1-969da6a83e36.png)

Im guessing this is not intended.

**Comment by FLasH3r** [comment]
@Doh09 - same here

link in button is `https://github.com/primer/octicons/archive/v9.1.1.zip` - returns 404
this link: `https://github.com/primer/octicons/archive/v9.1.0.zip` - works

**Comment by soarn** [comment]
Can reproduce!

**Comment by Doh09** [comment]
> @Doh09 - same here
> 
> link in button is `https://github.com/primer/octicons/archive/v9.1.1.zip` - returns 404
> this link: `https://github.com/primer/octicons/archive/v9.1.0.zip` - works

Worked with 9.1.0 as you stated.

**Comment by jonrohan** [comment]
Fixed
