### ISSUE TITLE
octicon-jersey looks like bulletproof vest

### ISSUE THREAD

**Issue by ianrandmckenzie** [primer/octicons#329]
I was creating a new organization on GitHub today, and in the breadcrumbs for Step 1, Step 2, etc. the Step 2. had the jersey icon. I immediately thought it had something to do with security because the jersey, to me, looked like a bulletproof vest. Here are some reference photos:
[Link 1](https://www.google.com/imgres?imgurl=https%3A%2F%2Fbac-tactical.com%2Fwp-content%2Fuploads%2F2018%2F04%2FVector-security-vest-front.jpg&imgrefurl=https%3A%2F%2Fbac-tactical.com%2Fshop%2Fsecurity-bulletproof-vest%2F&docid=hwJ8fbtLri7vGM&tbnid=HU5H5pM1FfjdZM%3A&vet=10ahUKEwjAoN2Yg6bjAhUSvZ4KHUHXBNUQMwiwAigIMAg..i&w=1400&h=2174&bih=1136&biw=1412&q=bulletproof%20vest&ved=0ahUKEwjAoN2Yg6bjAhUSvZ4KHUHXBNUQMwiwAigIMAg&iact=mrc&uact=8)
[Link 2](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ebayimg.com%2Fimages%2Fg%2Fy08AAOSwl8NVZQmX%2Fs-l640.jpg&imgrefurl=https%3A%2F%2Fwww.ebay.com%2Fp%2FSecpro-Concealable-Bulletproof-Vest-Made-With-Kevlar-NIJ-06-Level-IIIA-Large%2F1672995464&docid=1efyxBsPRz16EM&tbnid=APHX0quZR8o6cM%3A&vet=10ahUKEwjAoN2Yg6bjAhUSvZ4KHUHXBNUQMwizAigLMAs..i&w=600&h=600&itg=1&bih=1136&biw=1412&q=bulletproof%20vest&ved=0ahUKEwjAoN2Yg6bjAhUSvZ4KHUHXBNUQMwizAigLMAs&iact=mrc&uact=8)
[Link 3](https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.bladerunner.tv%2Fmedia%2Fcatalog%2Fproduct%2Fcache%2F1%2Fthumbnail%2F750x%2F17f82f742ffe127f42dca9de82fb58b1%2Fc%2Fo%2Fcovert-bullet-proof-vest_1.jpg&imgrefurl=https%3A%2F%2Fwww.bladerunner.tv%2Fcovert-vests-lightweight-bullet-stab-proof-vest-threat-level-ii.html&docid=bJ2fhEmEzFR3yM&tbnid=HZpaj1aQhACUhM%3A&vet=10ahUKEwjAoN2Yg6bjAhUSvZ4KHUHXBNUQMwiLAyhWMFY..i&w=750&h=750&bih=1136&biw=1412&q=bulletproof%20vest&ved=0ahUKEwjAoN2Yg6bjAhUSvZ4KHUHXBNUQMwiLAyhWMFY&iact=mrc&uact=8)

I think a possible solution would be to change one or both of the 1's on the jersey to a more identifiable number.

**Comment by yaili** [comment]
We are removing the jersey icon from Octicons V2, thanks for the feedback.
