### ISSUE TITLE
Add an Atom icon to the set

### ISSUE THREAD

**Issue by lee-dohm** [primer/octicons#34]
It would be useful to have an [Atom](https://atom.io) icon in the set for both Atom itself and web projects relating to Atom.

**Comment by mnquintana** [comment]
:+1: This would definitely be a useful addition

**Comment by casche** [comment]
:+1: agreed!

**Comment by EragonJ** [comment]
:+1: for this feature

**Comment by Huaraz2** [comment]
:+1:

**Comment by danielbayley** [comment]
+1.

**Comment by codynguyen1116** [comment]
+1

**Comment by danielbayley** [comment]
Maybe it could double as the smaller variants (namely 16 x 16 px, maybe 32 x 32…) of the `atom.icns` Application icon…

**Comment by shgysk8zer0** [comment]
This really wouldn't work well as an Octicon... At least not as  a font. You'll notice a lack of color in everything. 

If you want an SVG of the Atom logo, then here you go.
[Atom.svg](https://github.com/shgysk8zer0/logos/blob/master/atom.svg)

**Comment by lee-dohm** [comment]
I wasn't interested in it being a color version, really. I know icon fonts aren't built like that :grinning: But see here for an example of a colorless version in use on the [Atom website itself](https://discuss.atom.io):

<img width="213" alt="screen shot 2016-02-15 at 11 09 13 am" src="https://cloud.githubusercontent.com/assets/1038121/13057993/bab18984-d3d4-11e5-939b-2e0cd1885a07.png">
