### ISSUE TITLE
eye-closed and request-changes icons have non-16 height

### ISSUE THREAD

**Issue by dmitshur** [primer/octicons#346]
I'm not sure if this is intentional or not, but reporting to find out.

There are 191 octicons in v9.1.1. 189 of them have height set to exactly "16". But the recently added "eye-closed" and "request-changes" icons are the first to have non-16 heights:

- eye-closed has height "13.921463966369629"
- request-changes has height "15"

Possibly related, the vertical alignment of https://octicons.github.com/icon/eye/ and https://octicons.github.com/icon/eye-closed/ is slightly mismatched.

Is this working as intended or an unintentional bug?

/cc @colinkeany @katmeister

**Comment by yaili** [comment]
The icons in Octicons V2 are now all 1:1 aspect ratio, so this will be fixed.

**Comment by dmitshur** [comment]
That's great, thank you @yaili!

Over at https://octicons.github.com/, I see the currently released version is v9.3.1. Is there somewhere I could find more information about V2? Is PR #370 a good place to look?

**Comment by ashygee** [comment]
Hi @dmitshur, you can find information in our https://github.com/primer/octicons-v2 repo.
