### ISSUE TITLE
Sync icon circle shape

### ISSUE THREAD

**Issue by ababak** [primer/octicons#348]
The circle shape is not circled enough and the animated rotation is not ideal. This problem is the most noticeable when the spinning icon changes back to a static one.

![image](https://user-images.githubusercontent.com/11334363/64772297-05587680-d559-11e9-836d-ddd36f5bf092.png)

Here's a jsfiddle to see it live (note the circle edges floating around):
http://jsfiddle.net/ababak/zq8jrwhk/20/

I tried to play with `transform-origin: 51% 50%;` but the main problem is in the shape of the circle.

**Comment by yaili** [comment]
We will address this in Octicons V2. Thank you!
