### ISSUE TITLE
Proposal: Infinity and line-arrow icons

### ISSUE THREAD

**Issue by superbryntendo** [primer/octicons#349]
GitHub uses an infinity icon and a line-arrow on the pricing page and we'd like to use them in signup. Unfortunately, it appears that marketing had to use a non-octicons set to make those happen?

I've drafted up a couple icons to achieve the same stylistic goals while matching the octicons checkmark and x which are the most-used icons on these pages (provided for context below).

![image](https://user-images.githubusercontent.com/4926824/65466424-a1189b00-de13-11e9-8f09-fcd0f730519c.png)

The line-arrow icon is derived from the chevron octicon and is already in use in a signup flow experiment and I'd like to use the infinity icon in another one shortly. I think this would be a particularly nice addition especially since it'd let us support all of the cases on the pricing page too!

**Comment by yaili** [comment]
This has been done.
