### ISSUE TITLE
octicons/octiocons.css not in "main" of bower.json

### ISSUE THREAD

**Issue by andersjel** [primer/octicons#35]
According to http://bower.io/docs/creating-packages/, the "main" field of bower.json should list the primary acting files necessary to use your package. Doesn't this include `octicons/octicons.css`?

**Comment by lpsBetty** [comment]
+1

**Comment by jonrohan** [comment]
We've dropped support for bower, now using npm

**Comment by lpsBetty** [comment]
thanks, added it via CDN now ;)

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.5.0/octicons.min.css" />
```
