### ISSUE TITLE
Download link for 9.2.0 is broken

### ISSUE THREAD

**Issue by Schyzophrenic** [primer/octicons#355]
The website proposes to download the 9.2.0 [here ](https://github.com/primer/octicons/releases/download/v9.2.0/svg.zip) but the link is broken.

**Comment by kkauf** [comment]
What's the correct link? ;)

**Comment by Schyzophrenic** [comment]
Well, I'd say we should change 
`https://github.com/primer/octicons/releases/download/v9.2.0/svg.zip`
by
`https://github.com/primer/octicons/archive/v9.2.0.zip`

**Comment by AsgeirSH** [comment]
9.2 does not have an SVG archive available for download, only source code @Schyzophrenic. Maybe the build failed somehow? 

9.1.1 does, though: https://github.com/primer/octicons/releases/download/v9.1.1/svg.zip

**Comment by Schyzophrenic** [comment]
Right, I didn't realize these were actually 2 packages (first time I use octicons...) 
Thank you for pointing that out

**Comment by yaili** [comment]
This doesn't seem applicable anymore. Thank you for submitting.
