### ISSUE TITLE
Issue Notifications

### ISSUE THREAD

**Issue by corywilkerson** [primer/octicons#361]
The octicon for issue notifications appears to imply urgency (!)

I don't have an origin story for this octicon, but if I had to guess it would be something along the lines of:

1. A clever take on the letter "i"
2. An issue being tightly coupled with a bug and therefore requiring urgent/immediate attention

Can we explore introducing an alternative notification octicon for issues, introducing "i" in place of "!"? 

This might be a personal issue but I notice while triaging a large volume of notifications, my attention is unnecessarily drawn to "!" when often times there is little/no urgency behind the issue itself.

**Comment by lynnwallenstein** [comment]
+1, totally looks like something that needs emergency attention, even more so when it is in red.

I think it implies the wrong context of this is something that needs to be taken care of now versus indeed an issue (which I assume is why we don't call them bugs).

Would love to see us relook at this.

**Comment by shayfrendt** [comment]
*this* issue is very urgent

![urgent](https://user-images.githubusercontent.com/32535/68161881-cb866980-ff24-11e9-8570-a448ba869f70.png)

we should probably have it looked at immediately to help out @corywilkerson

**Comment by yaili** [comment]
Closing, we'll keep tracking in the linked issue.
