### ISSUE TITLE
color octicons used in css/less?

### ISSUE THREAD

**Issue by allefeld** [primer/octicons#364]
I'm trying to use Octicons as toolbar button icons within an Atom package. I have installed `octicons` as a dependency of the package, and now am able to use the SVGs like this in my stylesheet:

```
.toolbarButton#sidebarToggle::before {
  content: url(path/to/book.svg);
}
```

What I haven't been able to achieve is to color the icons in the same stylesheet. I assumed that something like

```
.toolbarButton#sidebarToggle::before {
  color: red;
  content: url(path/to/book.svg);
}
```

might work, but it doesn't. I suppose the reason is that the SVGs are embedded but their code is not affected by the embedding document's styles. Is there a way to achieve what I want?

I found ways to colorize using CSS filters, but none of the filters allow to simply specify the color. One can come up with suitable filter sequences, but the colors I'd like to apply exist as LESS color variables (from Atom's theme), i.e. they can change, and the relation between color and filter sequence is complicated.

I have seen that the package exposes a JavaScript interface which among other things allows to access the actual SVG code, which in principle would allow to inject a color, or to create an SVG element within the document which can then be styled. But if at all possible, I'd like to avoid programmatically changing document elements and stick to CSS/LESS.

**Comment by allefeld** [comment]
Alright, I now found <https://github.blog/2016-02-22-delivering-octicons-with-svg/> describing the move from webfonts to SVGs, and how SVGs linked in the HTML source apparently cannot be colored. This speaks for your Rails helper approach.

But Rails is server-side, which means I cannot use it in Atom. Correspondingly, the current Atom 1.14.0 still uses the webfont. (So you haven't made the replacement across *all* GitHub properties.)

**Comment by jonrohan** [comment]
@allefeld The icons are now checked into this repository so you should be able to use them in atom like you've shown above with the css.
