### ISSUE TITLE
Probably broken file/svg Figma download for 9.3.1

### ISSUE THREAD

**Issue by ollie** [primer/octicons#366]
Hello,

the readme states that the SVG file can be downloaded here: https://www.figma.com/file/FP7lqd1V00LUaT5zvdklkkZr/Octicons however when opening that link the only thing I see is this:

![octicons-figma](https://user-images.githubusercontent.com/53026/72425013-3ce56280-3787-11ea-90c0-4504de5daf44.png)

But there is nothing I can do on that page (excluding the sign-up). Am I missing something here? Or is it broken in some way? Funnily enough when you stay on that page for a while, you can see other people's hand roaming around in the same confused manner. (I tried this in latest Firefox and Chrome on a Mac.)

Thank you!

**Comment by connor-brooks** [comment]
I have the same issue, did you find a workaround?

**Comment by ollie** [comment]
Yeah, look here https://github.com/primer/octicons/issues/294#issuecomment-466594877.

If you have node/npm, you can `npm install octicons` somewhere and then copy those svgs from `node_modules/octicons/build/svg/`.

**Comment by marcomontalbano** [comment]
I have a different issue. Now the file is no more available? Is the link broken? ![image](https://user-images.githubusercontent.com/1681269/74105609-b04c7b00-4b5f-11ea-8025-dc50622b5fed.png)

**Comment by joseph-sx** [comment]
@marcomontalbano  try using this

> Yeah, look here [#294 (comment)](https://github.com/primer/octicons/issues/294#issuecomment-466594877).
> 
> If you have node/npm, you can `npm install octicons` somewhere and then copy those svgs from `node_modules/octicons/build/svg/`.

**Comment by colinkeany** [comment]
Closing this out as it appears to be resolved. Feel free to re-open if you're still having trouble.

**Comment by AdamBarnhard** [comment]
@colinkeany I think the Figma link is still broken here, I'm getting a Figma 404. Looks like a work-around with `npm` was proposed, but the broken link is still there.

**Comment by ollie** [comment]
@AdamBarnhard The icons are now part of the repo again https://github.com/primer/octicons/tree/master/icons, so Figma link is pretty much irrelevant now and readme doesn't mention it even anymore.
