### ISSUE TITLE
Include full copy-pastable SVG on website

### ISSUE THREAD

**Issue by fregante** [primer/octicons#369]
The [website](https://octicons.github.com/icon/arrow-both/) could have the whole SVG laid out, ready to be copied:

![](https://user-images.githubusercontent.com/1402241/73675113-6f2e1400-46e4-11ea-8a10-06f5d290e149.png)

**Comment by colinkeany** [comment]
We'll be resolving this in the very near future. Closing for now, please feel free to re-open if needed.
