### ISSUE TITLE
Create Icon for Draft Pull Requests

### ISSUE THREAD

**Issue by nschonni** [primer/octicons#376]
### What should the icon represent?

Draft pull requests represent an un-ready PR and would be treated differently from those triaging GitHub reviews

### Where will the icon be used?

https://github.com/notifications/

### Screenshots

Here is the new notification hub with Windows in High Contrast mode

![image](https://user-images.githubusercontent.com/1297909/75823693-354a3f00-5d70-11ea-8028-9f5a63cf6150.png)

With non-high contrast
![image](https://user-images.githubusercontent.com/1297909/75823940-9eca4d80-5d70-11ea-86a3-051946290b60.png)

The Draft and normal PR are currently indistinguishable for users requiring High Contrast mode as an accessibility requirements.

Spinning this off https://github.com/primer/octicons/issues/165 because this concept did not exist in 2017

**Comment by nschonni** [comment]
Icon now exists, and is differentiated by more than colour 🎆 
![image](https://user-images.githubusercontent.com/1297909/134443974-aa63d444-948c-4204-b3e2-1743ce3c43e3.png)

**Comment by shanevz** [comment]
Nice
