### ISSUE TITLE
Implementing 24px icons

### ISSUE THREAD

**Issue by colebemis** [primer/octicons#379]
I have some implementation questions regarding 24px icons that I'd like to discuss.

## Background

The current Octicons don't scale up well. When rendered at larger sizes, they look a little out of place:

![image](https://user-images.githubusercontent.com/4608155/76036537-3f4b7980-5ef9-11ea-92f9-e974410a754a.png)

In Octicons v2, to address this issue, we designed 24px icons (in addition to 16px icons) to handle cases where we need larger icons:

<img width="200" src="https://user-images.githubusercontent.com/4608155/76036451-03181900-5ef9-11ea-988d-f2def8c4b55f.png" />

**This means that our Ruby helper and React components now need to choose the right icon to render based on the size passed in:**

![image](https://user-images.githubusercontent.com/4608155/76033653-8e8dac00-5ef1-11ea-9c0a-425501b7d970.png)

I have a few questions about how to make that possible...

### File structure

How should we store the SVGs for each size? Here are a couple ideas: 

* Option A: Each size has it's own directory 
```
- icons/
  - 16/ 
    - git-pull-request.svg
  - 24/
    - git-pull-request.svg
```

* Option B: We have a flat directory of SVGs where each file name is the concatenation of the icon name and the size
```
- icons/
  - git-pull-request-16.svg
  - git-pull-request-24.svg
```

What are the advantages and disadvantages of these options? Is there an option I haven't considered?

### Data structure

Our Ruby and JavaScript APIs expose an object like this:

```
{
  alert: {
    keywords: ['warning', 'triangle', 'exclamation', 'point'],
    path: '<path d="M8.865 1.52c-.18-.31-.51-.5-.87-.5s-.69.19-.87.5L.275 13.5c-.18.31-.18.69 0 1 .19.31.52.5.87.5h13.7c.36 0 .69-.19.86-.5.17-.31.18-.69.01-1L8.865 1.52zM8.995 13h-2v-2h2v2zm0-3h-2V6h2v4z"/>',
    height: '16',
    width: '16',
    symbol: 'alert',
    options: {
      version: '1.1',
      width: '16',
      height: '16',
      viewBox: '0 0 16 16',
      class: 'octicon octicon-alert',
      'aria-hidden': 'true'
    },
    toSVG: [Function] 
  }
}
```

To support multiple sizes, we're going to have to update the structure of this object. How should the new object be structured?  Here's an idea:

```
{
  alert: {
    symbol: 'alert',
    keywords: ['warning', 'triangle', 'exclamation', 'point'],
    sizes: {
      16: { 
        height: '16',
        width: '16',
        path: '<path d="M8.865 1.52c-.18-.31-.51-.5-.87-.5s-.69.19-.87.5L.275 13.5c-.18.31-.18.69 0 1 .19.31.52.5.87.5h13.7c.36 0 .69-.19.86-.5.17-.31.18-.69.01-1L8.865 1.52zM8.995 13h-2v-2h2v2zm0-3h-2V6h2v4z"/>',
        options: {
          version: '1.1',
          width: '16',
          height: '16',
          viewBox: '0 0 16 16',
          class: 'octicon octicon-alert',
          'aria-hidden': 'true'
        },
        toSVG: [Function] 
      },
      24: ...
    }
    
  }
}
```

Do you see any potential problems with this structure? Is there a better way to structure this object?

### Non-square icons (i.e. logos)

How should we label the "size" of non-square icons like logos? For 16x16 icons, it's easy to label the size as "16." But for an icon that's 45x16, do we label the size as "45" or "16"?

---

Once we've answered these questions, I'll also need help implementing these changes in the Ruby libraries.

cc @jonrohan @joelhawksley

**Comment by joelhawksley** [comment]
This looks good, generally ❤️ . Some thoughts:

My personal preference would be to have the size in the filename.

Regarding the structure, wouldn't the CSS class be the same for both sizes?

Regarding the size, I wonder if we should explicitly refer to it as the `height`. 

At that point, each of the size objects would then only need a `width`, right?

**Comment by colebemis** [comment]
> My personal preference would be to have the size in the filename.

Out of curiosity, I'd love to hear your reasoning for that preference. Also, if we choose to go down that route, what should we do if a filename doesn't include a size? How can we enforce the naming convention?

> Regarding the structure, wouldn't the CSS class be the same for both sizes?

I agree that there's some redundancy in this object structure. Should we aim to make this object as minimal as possible? I believe the `options` object includes all the attributes that need to be applied to the `<svg>` element. So moving some attributes out of that `options` object might force developers to do some extra work. I'd love to hear from @jonrohan who has more historical context.

> Regarding the size, I wonder if we should explicitly refer to it as the height.

I'm good with that 👍

**Comment by joelhawksley** [comment]
Regarding the filename, I have a tendency to prefer filenames that are as explicit as possible, so one doesn't need the directory to know their full context.

Ah, I didn't think about how `options` would be use that way. I'm cool with keeping it as-is, as long as we have a way to ensure they match.

**Comment by colebemis** [comment]
> Regarding the filename, I have a tendency to prefer filenames that are as explicit as possible, so one doesn't need the directory to know their full context.

I'm onboard with this 👍 

There are a few edge cases I'm curious about:
* What should we do if a file name is not in the correct format (e.g. `circle.svg` instead of `circle-16.svg`)? Should we throw an error or should we parse the SVG to find the height? 
* What  should we do if the height in the file name does not match the actual height of the SVG (e.g. `circle-16.svg` contains `<svg height="24" ...>`)?  Should we throw an error or should we use the actual height of the SVG instead of the height from the file name?

**Comment by joelhawksley** [comment]
@colebemis if those things are part of a build step, I think it would make sense to implement those checks 👍

**Comment by colebemis** [comment]
@joelhawksley So you think it makes sense to abort the build if the file name is incorrect?

**Comment by joelhawksley** [comment]
It does! Always better to fail then than at runtime.

**Comment by colebemis** [comment]
### Implementation plan

Thanks for your help, @joelhawksley! Here's an implementation plan that incorporates the answers to my initial questions:

![image](https://user-images.githubusercontent.com/4608155/76553585-897caf80-6451-11ea-88c9-d55eb7088077.png)

---

### Notes

**[A] Files:** 

Here's an example of how the files will be renamed: `alert.svg` → `alert-16.svg` (where `16` is the height of the icon)

**[B] Build script:**

Here's how `data.json` (the output of the build script) will change:

```js
// Before
{
  "alert": {
    "name": "alert",
    "keywords: ["warning", "triangle", "exclamation", "point"],
    "width": 16,
    "height": 16,
    "path": "<path ... />"
  }
}
```

```js
// After
{
  "alert": {
    "name": "alert",
    "keywords: ["warning", "triangle", "exclamation", "point"],
    "heights": {
      "16": {
        "width": 16,
        "path": "<path ... />"
      },
      "24": {
        "width": 24,
        "path": "<path ... />"
      }
    }
  }
}
```

The build script will fail if:
* An SVG is missing `width` or `height` attributes (e.g. `<svg width="16" height="16" ...>`)
* A file name does not include the height (e.g. `alert.svg` instead of `alert-16.svg`)
* The height in the file name does not match the height of the SVG

**[C] Ruby:**

Here's how the Ruby API will change:

```rb
# Before
require 'octicons'
Octicons::Octicon.new("alert")
=begin
{
  :keywords => ['warning', 'triangle', 'exclamation', 'point'],
  :path => '<path d="M8.865 1.52c-.18-.31-.51-.5-.87-.5s-.69.19-.87.5L.275 13.5c-.18.31-.18.69 0 1 .19.31.52.5.87.5h13.7c.36 0 .69-.19.86-.5.17-.31.18-.69.01-1L8.865 1.52zM8.995 13h-2v-2h2v2zm0-3h-2V6h2v4z"/>',
  :height => '16',
  :width => '16',
  :symbol => 'alert',
  :options => {
    :version => '1.1',
    :width => '16',
    :height => '16',
    :viewBox => '0 0 16 16',
    :class => 'octicon octicon-alert',
    :'aria-hidden' => 'true'
  },
  :to_svg => [Function] 
}
=end
```

```rb
# After
require 'octicons'
Octicons::Octicon.new("alert")
=begin
{
  :symbol => 'alert',
  :keywords => ['warning', 'triangle', 'exclamation', 'point'],
  :heights => {
    :16 => {
      :path => '<path d="M8.865 1.52c-.18-.31-.51-.5-.87-.5s-.69.19-.87.5L.275 13.5c-.18.31-.18.69 0 1 .19.31.52.5.87.5h13.7c.36 0 .69-.19.86-.5.17-.31.18-.69.01-1L8.865 1.52zM8.995 13h-2v-2h2v2zm0-3h-2V6h2v4z"/>',
      :height => '16',
      :width => '16',
      :options => {
        :version => '1.1',
        :width => '16',
        :height => '16',
        :viewBox => '0 0 16 16',
        :class => 'octicon octicon-alert',
        :'aria-hidden' => 'true'
      },
      :to_svg => [Function] 
    },
    :24 => { ... }
  }
}
=end
```

**[D] JavaScript:**

Here's how the JavaScript API will change:

```js
// Before
const octicons = require("octicons")
octicons.alert
/*
{
  keywords: ['warning', 'triangle', 'exclamation', 'point'],
  path: '<path d="M8.865 1.52c-.18-.31-.51-.5-.87-.5s-.69.19-.87.5L.275 13.5c-.18.31-.18.69 0 1 .19.31.52.5.87.5h13.7c.36 0 .69-.19.86-.5.17-.31.18-.69.01-1L8.865 1.52zM8.995 13h-2v-2h2v2zm0-3h-2V6h2v4z"/>',
  height: '16',
  width: '16',
  symbol: 'alert',
  options: {
    version: '1.1',
    width: '16',
    height: '16',
    viewBox: '0 0 16 16',
    class: 'octicon octicon-alert',
    'aria-hidden': 'true'
  },
  toSVG: [Function] 
}
*/
```

```js
// After
const octicons = require("octicons")
octicons.alert
/*
{
  symbol: 'alert',
  keywords: ['warning', 'triangle', 'exclamation', 'point'],
  heights: {
    16: {
      path: '<path d="M8.865 1.52c-.18-.31-.51-.5-.87-.5s-.69.19-.87.5L.275 13.5c-.18.31-.18.69 0 1 .19.31.52.5.87.5h13.7c.36 0 .69-.19.86-.5.17-.31.18-.69.01-1L8.865 1.52zM8.995 13h-2v-2h2v2zm0-3h-2V6h2v4z"/>',
      height: '16',
      width: '16',
      options: {
        version: '1.1',
        width: '16',
        height: '16',
        viewBox: '0 0 16 16',
        class: 'octicon octicon-alert',
        'aria-hidden': 'true'
      },
      toSVG: [Function] 
    },
    24: { ... }
  }
}
*/
```

**[F, G, and H] Rails, Jekyll, and React:**

The packages will choose to render the SVG with a height that is less than or equal to the given height:

![image](https://user-images.githubusercontent.com/4608155/76554742-9a2e2500-6453-11ea-8081-52b871b2357f.png)

When passed in a width, we'll need to calculate the proportional height to determine which SVG to render. This might be tricky for icons that don't have equal width and height.

---
 
### Open questions

* Should this all be done in one PR? The Octicons packages and website will broken during the intermediate stages of this plan but it also seems like a lot of work to include in one PR.

---

cc @joelhawksley @jonrohan

**Comment by joelhawksley** [comment]
@colebemis we should be able to pull this off by shipping major releases of the relevant libraries, from the top to the bottom of that (wonderful!) tree diagram.

This is something I can take on in a week or so ❤️

**Comment by colebemis** [comment]
I was thinking we'd merge these changes into the `v2` branch. Then publish major releases of all the packages when we merge the `v2` branch. Did you have something else in mind?

Also, do you think each of the nodes in the tree should be separate PRs or should we do one big PR? We could also stack smaller PRs to make them easier to review without breaking the `v2` branch. That could look something like this:

![image](https://user-images.githubusercontent.com/4608155/76559015-969e9c00-645b-11ea-9072-9f31dc7ef728.png)

**Comment by joelhawksley** [comment]
@colebemis duh! `v2` is _already_ a major release. We can totally do this work as a branch we merge into the `v2` feature branch.

I can't imagine it being an issue to just do this in one PR.

**Comment by colebemis** [comment]
@joelhawksley Sounds good. I can start on this work and reach out to you when I get to the Ruby part 😄

**Comment by jonrohan** [comment]
All of this sounds great, and how I imagined it being implemented. What did we decide on dropping the acceptance of numerical values for height and width and instead moving to only the accepted sizes? Not sure if it would be better to say `size: 1` `size: 2` or `size: sm` `size: lg`

**Comment by joelhawksley** [comment]
@jonrohan what sizes are allowed seems to be more of an application/design-system requirement. 

I think it's fine for these libraries to  accept numerical sizes.
