### ISSUE TITLE
Simplify contribution workflow

### ISSUE THREAD

**Issue by colebemis** [primer/octicons#384]
## Problem

Our current contribution workflow has a few problems:
* It requires contributors to clone the [primer/octicons](https://github.com/primer/octicons) repo to their local machine.
* It requires familiarity with Git.
* It requires familiarity with SVG.
* There are a lot of unnecessary steps.

Here's a flowchart of the current contribution workflow:

![image](https://user-images.githubusercontent.com/4608155/76566630-64e10180-646a-11ea-8bef-a4a82777b118.png)

## Solution

Let's build a Figma plugin to allow contributors to open pull requests and commit to the [primer/octicons](https://github.com/primer/octicons) repo directly from Figma. Here's a wireframe of what the plugin could look like:

![image](https://user-images.githubusercontent.com/4608155/76566753-ac678d80-646a-11ea-84d3-d3aac9df1181.png)

The interface is modeled after the GitHub's web UI editor. Here's how I'm imagining the user flow would work:

1. Select the icon frames you want to add or update
1. Open the Figma plugin
1. Write a commit message (We could probably auto-populate a default commit message)
1. Click "Open pull request"
1. _Plugin exports and optimizes the selected SVGs and creates a new branch._ 
1. _Plugin redirects you to github.com to open a pull request with the new branch._
1. Write a detailed pull request description
1. Create pull request

Here's a flowchart showing how this plugin could simplify the contribution workflow:

![image](https://user-images.githubusercontent.com/4608155/76569226-d1aaca80-646f-11ea-93f5-81c79eaac696.png)

**Comment by ashygee** [comment]
Just adding this for extra notes on an octicons Figma plugin: https://pixelcat.githubapp.com/post/ck6mtmz2qig1i07703yzcjz28

![image](https://user-images.githubusercontent.com/10384315/76653915-fb72f880-6526-11ea-9a33-df0802cfcbf0.png)

**Comment by colebemis** [comment]
Addressed in https://github.com/primer/figma-octicons-push
