### ISSUE TITLE
Octicons v2 lightbulb clarification

### ISSUE THREAD

**Issue by superbryntendo** [primer/octicons#391]
I've been using the lightbulb icon on some mockups for GitHub Discussions and I often mistake it for a shoe.

I was wondering if we could tweak the bottom so it's more "lightbulb-y"

My initial idea was something to suggest threads:

![image](https://user-images.githubusercontent.com/4926824/78199339-3ee2c780-7440-11ea-8a00-9484d98db675.png)

Obviously not perfect implementation, but wanted to get opinions before tweaking it...

/cc @ashygee @colebemis

**Comment by edokoa** [comment]
I added this to Octicons Feedback

 https://github.com/github/design-systems/issues/765

**Comment by ashygee** [comment]
@superbryntendo totally valid feedback. If you have a figma link please share because I'd like to explore this direction a bit with @edokoa and @colebemis

**Comment by ashygee** [comment]
@edokoa here are the explorations i had started with for our current lightbulb icon. https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=0%3A29886

**Comment by edokoa** [comment]
I did a few explorations.
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=983%3A2121

With the Octicon styles it's difficult to depict threads, as close horizontal lines are difficult and tend to get muddy when scaling down, but those are the ones I think work better from the ones I was trying:

![image](https://user-images.githubusercontent.com/694831/78795953-f2563980-79b5-11ea-897f-a68c0fcc4c43.png)

**Comment by edokoa** [comment]
We were discussing this again at the Octicons meeting and we decided we will advance with this one that Cole proposed:

https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=983%3A2389

![image](https://user-images.githubusercontent.com/694831/78830099-b63bcc80-79e7-11ea-940c-4cf7f5d3bd32.png)

I will work on the 24/48 px version tomorrow.

**Comment by edokoa** [comment]
I made this version for 48/24
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=997%3A1924

![image](https://user-images.githubusercontent.com/694831/78887053-80d2c580-7a5f-11ea-93af-f37e38e7672f.png)

I was testing different variations and I think it's the one that works the best with element gaps and pixelation when resizing

![image](https://user-images.githubusercontent.com/694831/78887278-dc04b800-7a5f-11ea-8740-ba1f3a6a595c.png)

**Comment by colebemis** [comment]
Closed by #400

**Comment by superbryntendo** [comment]
Looks great! Thanks 🙏
