### ISSUE TITLE
[Suggestion] Add support for img-tags in html files

### ISSUE THREAD

**Issue by Andre601** [primer/octicons#394]
I would love to use some of the Octicons in my site. In fact does the theme I use ship with basic support for Octicons, although not for sites themself, but only specific parts.

I'm sure a lot of people would agree that it would be a very useful thing to have support for Octicons in `<img>` tags, for easier integration.
As of now did I not find a way to integrate those icons into an HTML site, except for using the `<svg>` tag in combination with the `<path>` tags, which isn't that optimal (and also doesn't look that pretty, even for HTML).

If - for whatever reason - you don't quite understand what I'm requestion, do I have an example here with adding an emoji from [Twemoji](https://twemoji.twitter.com/) used for a h1-header of a 404-page.
```html
<h1>4<img alt="😦" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f626.svg" title=":frowning:">4 - Not Found</h1>
```

**Comment by jonrohan** [comment]
I believe all browsers support `<img>` tags with svg. https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web#The_quick_way_%3Cimg%3E 

If you download the icons https://github.com/primer/octicons/tree/master/icons and include on your site, you should be able to link them. If you want somewhere to hotlink there's unpkg https://unpkg.com/browse/@primer/octicons@latest/build/svg/  But I can't guarantee the performance there. Storing them somewhere else would be better for your site.
