### ISSUE TITLE
[Icon request] Container icon

### ISSUE THREAD

**Issue by pmarsceill** [primer/octicons#426]
### What should the icon represent?

A container (e.g., Docker container, but generic)

### Where will the icon be used?

GitHub Packages w/ container support

### Screenshots

![image](https://user-images.githubusercontent.com/896475/82600049-4179b780-9b7b-11ea-9546-9e2db56cd9a8.png)

(in place of the "Package" icon)

**Comment by ashygee** [comment]
After speaking with @pmarsceill this icon will appear in two spots within our UI

**List view**: https://github.com/orgs/github/packages?ecosystem=container
![screenshot of packages list view showing container icon at 20px sizing](https://user-images.githubusercontent.com/10384315/94186253-758c1e80-fe74-11ea-9c3d-8e8c502b5ccc.png)

Here we are currently using the logo of the container type at 20px

**Detail**: https://github.com/orgs/github/packages/container/package/super-linter
![screenshot of package details showing container icon at 36px sizing](https://user-images.githubusercontent.com/10384315/94186406-acfacb00-fe74-11ea-897b-a6a3d28fdfe1.png)
Here we are currently using the logo of the container type at 36px

The main issue is that neither view uses the icons at the base size we have for 16px or 24px so there would be slight scaling unless we correct the sizing to use our default sizing.

With that in mind, here are some initial explorations for the `container` icon

![6 exploration of container icon](https://user-images.githubusercontent.com/10384315/94186103-41b0f900-fe74-11ea-8c53-7b4dc6c9984c.png)

cc @colebemis @edokoa @pmarsceill

**Comment by edokoa** [comment]
I think I'd prefer the style of the larger one instead of adding more detail. I'd try how it looks with the package icon to try to keep perspective.

**Comment by pmarsceill** [comment]
Cc @ramazu

**Comment by ramazu** [comment]
I could see the `larger` and `shallow` options working well. Can you send these over individually so I can test within my mockups @ashygee?

**Comment by colebemis** [comment]
Hi, @ramazu. Sorry for the delay! I looked through our Octicons Figma file and I couldn't find the source for these icons. I'll have to ask @ashygee when he gets back.

**Comment by colebemis** [comment]
@ramazu A little birdie sent me the Figma link 😄  Here ya go: https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2---Source?node-id=3227%3A71

**Comment by ramazu** [comment]
Thanks @colebemis!!

**Comment by ashygee** [comment]
<img width="301" alt="fixed perspective of container icons with the package icon as a reference" src="https://user-images.githubusercontent.com/10384315/96771747-f9afc400-1396-11eb-802f-934f26be8b51.png">

@ramazu after some discussion @edokoa has fixed the perspective for these icons as well as simplified the look. These two variations cater more to the minimal/simple styling that fits better with the larger set of Octicons. You can grab them from figma and test them in your mocks.

Thoughts?

cc @pmarsceill

**Comment by ramazu** [comment]
Thanks! Off the bat – I prefer the icon `w/ lines`, considering there will be cases when the container icon will be in close proximity to the generic package icon. 

I will explore to confirm.

**Comment by ashygee** [comment]
@ramazu any feedback on this?

**Comment by ramazu** [comment]
I've been using the `w/ lines` in my mockups and works really well. Can we add this to the Octicons set?

<img width="1680" alt="Packages (GHCR opt-in)" src="https://user-images.githubusercontent.com/4925665/98203428-eb11f280-1ee8-11eb-98b0-e3fe817e799b.png">

**Comment by ashygee** [comment]
Added in #510
