### ISSUE TITLE
[Icon request] `bug` missing from v2

### ISSUE THREAD

**Issue by fregante** [primer/octicons#430]
v1: https://github.com/primer/octicons/blob/master/icons/bug.svg 🐛 
v2: https://github.com/primer/octicons/blob/v2/icons/bug.svg ❌ 

Was the removal intentional?

**Comment by FloEdelmann** [comment]
The icon is actually included again in v10, although the release notes say the opposite: #448

**Comment by fregante** [comment]
🎉 
https://github.com/primer/octicons/blob/master/icons/bug-16.svg

**Comment by colebemis** [comment]
We put the old bug octicon back but we do plan to redesign it in the new style :)
