### ISSUE TITLE
Improve rendering on non retina displays

### ISSUE THREAD

**Issue by sampotts** [primer/octicons#432]
It seems the icons don't render well at all on non retina due to a lot of half pixels. It might be worth giving them a once over and cleaning up the co-ordinates so they render crisply?

![image](https://user-images.githubusercontent.com/719092/83199100-e00da600-a183-11ea-9b4d-cd54fda2f9d3.png)

![image](https://user-images.githubusercontent.com/719092/83199119-e734b400-a183-11ea-9486-9c04e93bd676.png)

![image](https://user-images.githubusercontent.com/719092/83199158-fd427480-a183-11ea-9661-cff900b88539.png)

![image](https://user-images.githubusercontent.com/719092/83199172-06334600-a184-11ea-8410-84e9b5e3de4d.png)

![image](https://user-images.githubusercontent.com/719092/83199184-0d5a5400-a184-11ea-8a2f-ddd45ed17805.png)

![image](https://user-images.githubusercontent.com/719092/83199270-38dd3e80-a184-11ea-95af-aaed4b12df36.png)

![image](https://user-images.githubusercontent.com/719092/83199299-44306a00-a184-11ea-8083-d37262fbed8b.png)

**Comment by Geo1088** [comment]
This is a bit of a frustrating change coming from the old icons for me. I like the changes to the icon designs themselves, but the blurry display makes them look awful compared to the old ones to me.

**Comment by ajarouih** [comment]
Same problem here.

**Comment by eritbh** [comment]
Is there any hope of this being addressed? Icons on Github still look fuzzy and messy in a lot of places, and while it's definitely something I've gotten used to over time, it's still annoying knowing that the set before the big change displayed crisply on normal screens. Even if the stroke width is something that's not going to be changed, it'd be nice to at least get an acknowledgement of the feedback or something.

**Comment by yaili** [comment]
👋🏼  We'll add this to the team's discussion agenda and will update this issue when we know more. Thanks for opening this issue and keeping it active. 🙂

**Comment by colebemis** [comment]
Thank you for the feedback, @sampotts. 

Half-pixels on non-retina displays was an intentional design tradeoff that we accepted when we decided to move forward with 1.5px stroke for our icons. 

In our initial design explorations, 1px stroke felt a little too thin and 2px felt a little too thick. 1.5px stroke was a nice middle-ground.
