### ISSUE TITLE
Pull request closed icon

### ISSUE THREAD

**Issue by taywrobel** [primer/octicons#454]
### What should the icon represent?

This icon should visually represent a pull request that has been closed.

The icons for closed and open pull requests are currently the same, distinguished only by color (green for open, red for closed). This is extremely problematic for color blind users, particularly those with Protanopia [1] or Deuteranopia [2]. See simulated views in the screenshots below.

### Where will the icon be used?

To be used in the PR list and other locations where `octicon-github-pull-request closed` CSS classes are used.

### Screenshots

PR list with closed, open, merge, and draft PRs with a view demonstrating [simulated](https://www.color-blindness.com/coblis-color-blindness-simulator/)

[1] Protanopia:

<img width="151" alt="Screen Shot 2020-06-15 at 9 30 24 PM" src="https://user-images.githubusercontent.com/1165951/84732044-76491680-af4f-11ea-8175-ca43e812f304.png">

[2] Deuteranopia:

<img width="153" alt="Screen Shot 2020-06-15 at 9 30 33 PM" src="https://user-images.githubusercontent.com/1165951/84732071-8c56d700-af4f-11ea-90c3-93c090a3fbaa.png">

**Comment by edokoa** [comment]
@Juliusschaeper is working on alternative icon designs to avoid this problem.

https://github.com/github/design-systems/issues/873

**Comment by adrinjalali** [comment]
I think that's a private repo and we can't see the progress?

**Comment by edokoa** [comment]
Sorry, I was posting a link to a private repo to reference the other related issue. It includes internal work which prevents it from being public, but we will update this issue with new information when we can.

**Comment by ashygee** [comment]
This work is being tracked here: github/design-systems#1286
