### ISSUE TITLE
[Icon request] Internal

### ISSUE THREAD

**Issue by simurai** [primer/octicons#460]
### What should the icon represent?

"Internal". Or something in between public and private.

### Where will the icon be used?

It currently gets used when creating a new repo in an org that is part of an enterprise:

```
https://github.com/organizations/ORG/repositories/new
```

Let me know if I should invite someone to see a live example.

### Screenshots

Currently the icon is custom made and directly inlined as SVG.

![Screen Shot 2020-06-30 at 9 57 56](https://user-images.githubusercontent.com/378023/86070796-85d06f80-bab8-11ea-92ee-dfcf6131aab2.png)

**Comment by ashygee** [comment]
Hi @simurai we addressed the internal repo icon treatment in this [issue](https://github.com/primer/octicons-v2/issues/300)

Our solution is to use the 16px `repo` icon and overlay the avatar of the organization.

![image](https://user-images.githubusercontent.com/10384315/91881967-29640a80-ec37-11ea-978e-0482dc88b715.png)
