### ISSUE TITLE
[Icon request] TAs and Admins / Students

### ISSUE THREAD

**Issue by brooklynO** [primer/octicons#479]
### What should the icon represent?

We are currently using the "people" icon for Students in our nav on Classroom. We need an icon that represents "TAs (teacher assistants) and Admins" a teacher may have added to their Classroom. Currently a wrench is being used, have also tried the org building.. but it should show people. 

An alternate could be that we come up with one for "students" and then use the generic "people" for TAs and Admins. It's just important for the teacher to distinguish between their students and their TAs but make it clear both are humans and not settings :) 

### Where will the icon be used?

It will be used in the navigation on Classroom in the context of 3 other tabs: 
Assignments / Students / TAs & Admins / Settings
You'll need to be signed in as a teacher to be able to see the link live, but the screenshot below should suffice to show the context. 
https://classroom.github.com/classrooms/32969127-cs-classroom-org-classroom-12/settings/invitations

### Screenshots

<img width="1011" alt="Screen Shot 2020-07-31 at 11 24 17 AM" src="https://user-images.githubusercontent.com/43388877/89065737-194bc900-d321-11ea-801b-16aa70779464.png">

**Comment by edokoa** [comment]
As discussed in the Octicons meeting, do we really need new icons for those or can it be solved with badges / labels / copy?

**Comment by brooklynO** [comment]
As I just discussed with Ash, I think the icon use in Classroom is a bit convoluted, and adding an icon for TAs just to support the current tab design I'd like to eliminate isn't worth it. We can close/cancel this request.
