### ISSUE TITLE
Polish custom GH desktop icons

### ISSUE THREAD

**Issue by ashygee** [primer/octicons#490]
The Desktop team recently updated the octicons in the app and we need to polish so that they follow the octicons design guidelines.

### Icons needed
- [ ] arrow-small-up
- [ ] arrow-small-down
- [ ] stash
- [ ] force-push
- [ ] co-author

### Current design
**Co-author**
![person icon with a plus icon](https://user-images.githubusercontent.com/10384315/91339709-b583b700-e78b-11ea-98b6-1d04079ce282.png)

**Force push**
![up arrow with two arrow heads](https://user-images.githubusercontent.com/10384315/91339807-d946fd00-e78b-11ea-81c2-85522f1f3019.png)

**Stash**
![stacked modifier icons](https://user-images.githubusercontent.com/10384315/91339836-e8c64600-e78b-11ea-8651-9c68a6bfedf1.png)

**Small arrows**
![image](https://user-images.githubusercontent.com/10384315/91339939-0c898c00-e78c-11ea-9405-cad5afbb2801.png)

**Comment by edokoa** [comment]
Do we aim to keep the different size viewports, or will we work with fixed size (16x) icons and then decide whether we want to crop them or not?

This also opens the question of being able to crop whitespace in icons.

**Comment by edokoa** [comment]
For `force-push` we had this variant that we didn't include in the set. It also depends on how the push icon used in the app looks
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=5395%3A4487

![image](https://user-images.githubusercontent.com/694831/101760125-c35f0d00-3ada-11eb-94c2-b471b98e8183.png)

**Comment by edokoa** [comment]
Regarding the `add user` icon, we'll be working on modifiers after EOY, but I'd consider this, taking into account how the `user` and `group`: https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=5395%3A4619

![image](https://user-images.githubusercontent.com/694831/101761107-0d94be00-3adc-11eb-8798-4239a867a653.png)

This also opens the question of custom size icons in the app, and the need to make them consistent so it matches .com and works with the rest of the Octicons set.

**Comment by edokoa** [comment]
About the arrows. I don't have the exact size it has to display into, but those are the fold arrows with and without a line. The decision of making the arrowhead solid was an stylistic decision that depends on the size of the arrow more than the function it serves, as line arrows are difficult to render below certain size.
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=5395%3A4647
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=5395%3A4723

![image](https://user-images.githubusercontent.com/694831/101762806-2d2ce600-3ade-11eb-9fce-2f2fd55eaacc.png)
![image](https://user-images.githubusercontent.com/694831/101762827-328a3080-3ade-11eb-8630-35758b30a367.png)

**Comment by edokoa** [comment]
About the `stash` icon, if we want to keep the same methaphor it'd have to be like this. I've been trying to fit 3 layers in the space we have but they become blurry when scaling down to 16px
https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2-Source?node-id=5395%3A10199

![image](https://user-images.githubusercontent.com/694831/101765168-3d929000-3ae1-11eb-8e5c-871f07d83765.png)

**Comment by ashygee** [comment]
Hi! We're going to add the `person-plus` (add co-author) icon t octicons but would like an update on the rest of the icons. cc @ampinsk
