### ISSUE TITLE
Alignment needs fixing

### ISSUE THREAD

**Issue by ashygee** [primer/octicons#502]
@vdepizzol mentioned this to me yesterday:

![screenshot of go to file button and kebab octicon out of alignment](https://user-images.githubusercontent.com/10384315/96616309-44f2a580-12b7-11eb-81f7-c9ba5eec7f3f.png)

> our octicon buttons should definitely have 32x32px in total size, I wonder how we could fix that with all the existing instances already in place

**Comment by colebemis** [comment]
This seems like an issue we could fix in Primer CSS/ViewComponents/React. We could have an icon button component with extra padding to increase the touch area.
