### ISSUE TITLE
Documentation site is squishing images on Safari, macOS

### ISSUE THREAD

**Issue by brianlovin** [primer/octicons#504]
Page: https://primer.style/octicons/guidelines/design

Screenshot of the bug:
![Screen Shot 2020-10-29 at 1 06 56 PM](https://user-images.githubusercontent.com/1923260/97626848-b92ff600-19e7-11eb-9806-b9d0fdb7221e.png)

**Comment by colebemis** [comment]
Thanks for flagging this, @brianlovin!

**Comment by yaili** [comment]
I can't replicate this anymore 🙂
