### ISSUE TITLE
Zoom-to-fit icon for Actions visual graph

### ISSUE THREAD

**Issue by jasonlong** [primer/octicons#506]
### What should the icon represent?

The icon represents the fitting of all contents into the visible area.

### Where will the icon be used?

With the new visual graph for Actions, you're able to see all of the jobs in a running (or previously run) workflow. You're also able to zoom in which is especially useful when there are a lot of jobs in the graph. The new icon would replace the "Fit to window" button here.

![image](https://user-images.githubusercontent.com/6104/98174385-ce62c400-1ec2-11eb-8c91-e4666f000d65.png)

### Screenshots

We were thinking of an icon along these lines:

![image](https://user-images.githubusercontent.com/6104/98139370-1fa68f80-1e92-11eb-8bc4-23238b9c39db.png)

**Comment by colebemis** [comment]
Would `screen-full` work? https://primer.style/octicons/screen-full-16

**Comment by yujincat** [comment]
@jasonlong Do we have a conclusion on this? I am not sure which one is final but the issue is closed .
