### ISSUE TITLE
Icons font for desktop applications

### ISSUE THREAD

**Issue by Eng3l** [primer/octicons#516]
I'm developing an app with Qt+QML and using icons as svg works well but I think that having icons in a ttf font is more efficient and is more easy to work with.

Thanks for this amazing project.

**Comment by yamatsum** [comment]
I made icon font based on octicons.
If you like, give it a try
https://github.com/yamatsum/nonicons

**Comment by ashygee** [comment]
@Eng3l Thanks for the suggestion. We may expand the implementations of Octicons in the future but at this time we don't have plans for this. It sounds like the library that @yamatsum might fit your needs though! We appreciate the feedback 😄
