### ISSUE TITLE
Icons for Advisory Inbox [Icon request]

### ISSUE THREAD

**Issue by bochong** [primer/octicons#521]
### What should the icon represent?

We need 3 different icons: 
1. double chevron left 
![image](https://user-images.githubusercontent.com/42078122/101672353-005fcc80-3a13-11eb-8975-66a602a79780.png)

2. double chevron right

3. icon for advisory reviews 
![image](https://user-images.githubusercontent.com/42078122/101672401-0eade880-3a13-11eb-8c71-a910bdce70d9.png)

### Where will the icon be used?

These icons will be used in the Advisory Inbox, which is an internal product that will be used to assist in advisory curation. 
https://www.figma.com/file/B8ZIJkOVZ4SWu9Ydd5MlIr/Advisory-Inbox?node-id=1%3A27

### What is the timeline?
If we could get these icons early next year that'd be great. 

### Screenshots

![image](https://user-images.githubusercontent.com/42078122/101672149-bc6cc780-3a12-11eb-8ca4-a92b29f50a11.png)

**Comment by ashygee** [comment]
@bochong I've added your icon request to our project board. Is there a designer you're working with on this project or are you the point person to chat with directly?

**Comment by edokoa** [comment]
Pinging @bochong again here.

We're in the process of reorganizing our processes and going through open requests. Do you have any input on what @ashygee was asking in the previous comment? What is the current status of this project?

**Comment by bochong** [comment]
Hello @ashygee @edokoa, sorry for the late reply. Seems like I didn't get any email notifications for this for some reason. This project is currently being implemented and the designer was @ichelsea I believe. The designs are not actively being worked on at the moment past the linked figma, so you can chat with me directly or ping us in the #advisory-inbox-engineering channel. 

I believe we also will not need icon 4 in the description, so I will update that as well.

**Comment by bochong** [comment]
Closing as due to design changes, we will not be needing these icons anymore!
