### ISSUE TITLE
Arrow up 24px is smaller than other arrows

### ISSUE THREAD

**Issue by peplow** [primer/octicons#530]
Arrow up 24px is only about 12x16px while all other 24px arrows are about 18x14px in size. Not shure if this is intended, however it looks unproportional to me.

**Comment by ashygee** [comment]
Thanks for pointing this out @peplow! I've marked this as a bug and will triage this in our next release.

**Comment by ashygee** [comment]
@peplow this has been added in release 14.0.0! Thank you!
