### ISSUE TITLE
Naming discrepancy of `trash` and `trashcan` icons?

### ISSUE THREAD

**Issue by fermion** [primer/octicons#537]
👋🏻 noticed this while using the `octicons_helper` gem in conjunction with primer on a personal project. It looks like the two trash can icons have different names depending on the target size used, `trash` for 16px and `trashcan` for 24px.

I forked the repo and was going to submit a PR to update the file name but I wanted to check and see if the name mismatch was intentional. Thanks in advance ✨

**Comment by colebemis** [comment]
Nice catch! That was not intentional. We'd love a PR ❤️ Let's call them both `trash`

**Comment by camilogarcialarotta_emusand** [comment]
<string>

**Comment by camilogarcialarotta_emusand** [comment]
<string>

**Comment by camilogarcialarotta_emusand** [comment]
<string>

**Comment by camilogarcialarotta_emusand** [comment]
<string>

**Comment by camilogarcialarotta_emusand** [comment]
<string>

**Comment by ashygee** [comment]
@fermion this update has been included in our [v12.0.0](https://github.com/primer/octicons/releases/tag/v12.0.0) release :)
