### ISSUE TITLE
Allow custom props/attributes + Allow custom-ratio icons (e.g. 14x16)

### ISSUE THREAD

**Issue by fregante** [primer/octicons#557]
Check out: https://github.com/marketplace/actions/fortify-scancentral-scan
The icons in the sidebar have `viewBox="0 0 16 16" width="14" height="16"`. 

This is currently not possible with this package because props other than predefined ones are ignored, so `<SearchIcon width="14"/>` is equivalent to `<SearchIcon"/>`

`<SearchIcon style={{width: '14px'}}/>` is also ignored.

Can you add a `...props` and/or `...props.style` in `getSvgProps`?

**Comment by fregante** [comment]
I'd still like to see this

**Comment by fregante** [comment]
I'd still like to see this

**Comment by colebemis** [comment]
We intentionally prevent custom-ratios in octicons to avoid distorting the icons. There's more information in our usage guidelines: https://primer.style/octicons/guidelines/usage#sizing
