### ISSUE TITLE
[Icon request] Any way to use concept/rejected icons?

### ISSUE THREAD

**Issue by lowlighter** [primer/octicons#559]
This issue is not a really an "Icon request" per se, but is there a way to re-use concepts icons that did not make it in final release?

I'm asking that because I noticed that some early concepts presented here are actually interesting and could be actually be used (like in https://github.com/primer/octicons/issues/539#issuecomment-786758332) by others even if GitHub don't use them. 

As the work already done, it wouldn't be too hard to share it I guess

___

Thanks again for your work and open-sourcing it, these icons are really nice 🙂

**Comment by ashygee** [comment]
Hi @lowlighter, sorry but there is no way to use the concepts as they are not part of the octicons library. Thank you for your support!
