### ISSUE TITLE
Icon request for Global Campus

### ISSUE THREAD

**Issue by sezhan1229** [primer/octicons#572]
#### What should the icon represent?

We need 2 icons that represent Student Developer Pack and Campus Expert. We have the full color logos below. 
The icons need to reflect the 2 logos, same meanings, so people can recognize them.  Maybe just a simple backpack and a flag

#### Where will the icon be used?

The 2 icons will be used on Global Campus page. 

#### What is the timeline? Is this critical for a launch event?

The Global Campus site will be launched in July, but the engineers are actually implementing the site now. So It would be better to get them soon. 

#### Screenshots

These are the 2 logos we have now. 
More context is here: https://education.github.com/students

![image](https://user-images.githubusercontent.com/47256527/113254143-11ab3e00-927b-11eb-9ff3-a85350024dc4.png)

This is the place we will need the icons. Now I just use the person and star icons to be the placeholder. 

![image](https://user-images.githubusercontent.com/47256527/113913110-c91ae580-9790-11eb-8340-be0fc7ba8930.png)

**Comment by sezhan1229** [comment]
For the deadline, the team prefer to having the icons ready at least the end of May, but it wouldn't be a big issue for them to make the later change.

**Comment by ashygee** [comment]
Hi @sezhan1229, a quick note:

The flag causes some concern as it is typically used to reference alert/reporting actions. A suggestion we thought of might be something that has less of a negative connotation such as glasses, but we understand that might feel a bit off. I think the use of the `person` icon that you have as a placeholder already works well though as it is calling out a single person.

**Comment by sezhan1229** [comment]
@ashygee Thanks for leaving the note! I see your consideration here. 

I am thinking if we can tweak the person icon a bit more to let it be more specific for the Campus Expert (or education related)? Maybe something like this 👨‍🎓 ? Since the person icon is too generic. But I am also open to other suggestions.

**Comment by yaili** [comment]
Updated request link: https://github.com/github/primer/issues/96
