### ISSUE TITLE
The 16px `circle` icon is slightly mis-aligned

### ISSUE THREAD

**Issue by simurai** [primer/octicons#583]
Reported by @laserlemon in [Slack](https://github.slack.com/archives/C0ZCGGGJ2/p1617630391188200)

> i just wanted to point out that the (new?) circle octicon doesn’t seem to actually be a perfect circle at the 16px size. see: https://primer.style/octicons/circle-16 vs https://primer.style/octicons/issue-opened-16. the top is flattened. 24px looks

I didn't really see it, but when taking a screenshot and then zooming in with "render pixels" in Sketch, it seems that the circle is slightly off center and maybe needs to be nudged a tiny bit?

![Screen Shot 2021-04-05 at 22 55 19](https://user-images.githubusercontent.com/378023/113582078-e6519600-9662-11eb-85cb-55b05b35f0c6.png)

**Comment by laserlemon** [comment]
it could just be how it’s rendered in primer.style but the flat spots on the top and left were clearer there:

<img width="517" alt="Screen Shot 2021-04-05 at 10 04 35 AM" src="https://user-images.githubusercontent.com/34264/113582487-70afe080-95f6-11eb-8123-3d9ea2955017.png">

**Comment by laserlemon** [comment]
Strangely, this didn't close when https://github.com/primer/octicons/pull/584 landed. I'd close it myself but I'm not allowed! 🙈
