### ISSUE TITLE
octicon-logo-github has a bunch of extra whitespace at the bottom

### ISSUE THREAD

**Issue by mnquintana** [primer/octicons#59]
Compared to other Octicons, [`.octicon-logo-github`](https://octicons.github.com/icon/logo-github/) has a lot of extra whitespace at the bottom, which ends up meaning that in practice, it needs to be treated specially from other Octicons (ie. the extra bottom margin is removed to make it consistent and align with other Octicons).

Hopefully the screenshot makes the bottom margin difference clear enough:
![screenshot 2015-06-20 22 36 18](https://cloud.githubusercontent.com/assets/823545/8270118/dea34d86-179c-11e5-8c58-a490e350a915.png)

**Comment by tarebyte** [comment]
@cameronmcefee any idea why this is?

**Comment by cameronmcefee** [comment]
My first guess is that it's because the icons were optimized for use in 16pt lines. Or it could just be an oversight. We'll have a look at it in future versions.

cc @aaronshekey

**Comment by jonrohan** [comment]
fixed in #89
