### ISSUE TITLE
Inconsistent name for fork icon

### ISSUE THREAD

**Issue by octosteve** [primer/octicons#591]
![image](https://user-images.githubusercontent.com/325485/114106398-a8d84d00-989c-11eb-9dda-9f6e3cb3a394.png)

The fork icon is under 2 different names for different sizes. `repo-forked` for the 16px icon, and `git-fork` for the 24px icon.

**Comment by ashygee** [comment]
Thanks for noticing this @octosteve! We'll make the change in the next octicons release. 

Cc @colebemis
