### ISSUE TITLE
[Feedback] Incorrect metaphor for copy action

### ISSUE THREAD

**Issue by vdepizzol** [primer/octicons#606]
Looking at UIs around (and [historically](https://user-images.githubusercontent.com/293280/115763012-ea66fe80-a358-11eb-866b-0ff3a22b4472.png)), "Copy" is usually represented as two sheets of paper, while "Paste" is a clipboard. Searching Google for "copy icon" and "paste icon" also gives an idea.

> ![Screen Shot 2021-04-22 at 10 47 09](https://user-images.githubusercontent.com/293280/115762874-c4d9f500-a358-11eb-917a-0a68a8365805.png)
> Google Docs using Cut/Copy/Paste icons

Looking at `copy` actions throughout GitHub, it uses a clipboard icon ![clippy](https://user-images.githubusercontent.com/293280/115763305-3154f400-a359-11eb-8049-9d22853e75b6.png). However, a clipboard is used for representing the paste action, not, not copying. I think Octicons should have a more common two-sheets-of-paper metaphor for copy actions.

🙇

**Comment by laserlemon** [comment]
FWIW, the `duplicate` icon exists in latest versions and is the two sheets of paper you describe!

**Comment by ashygee** [comment]
@vdepizzol I've updated dotcom in regards to your feedback. Any thoughts? https://github.com/github/github/pull/185117

cc @Juliusschaeper

**Comment by ashygee** [comment]
@colebemis informed us that we should make the name change first before pushing the PR from above. 
https://github.com/github/github/pull/185117#pullrequestreview-716145167
