### ISSUE TITLE
[Feedback] Add Download All Option

### ISSUE THREAD

**Issue by circlePulse** [primer/octicons#620]
UI Feedback
## Add Download All Button

_It would be nice if [the Octicons Download Page](https://primer.style/octicons/) had a button to download all icons. I am importing the icons to [Nucleo](https://nucleoapp.com/) and its a pain to download them individually._ 

### Thanks!
**P.S. Great icons!!**

**Comment by ashygee** [comment]
Hi @circlePulse thanks for your feedback. You can download all of the icons from our [Figma community file](https://www.figma.com/community/file/809920999413919915/Octicons---GitHub's-icon-set). Thank you!

**Comment by circlePulse** [comment]
But... I don't use Figma
