### ISSUE TITLE
[Bug] Sort Ascending/Descending size 24 rendered as a filled square

### ISSUE THREAD

**Issue by metonym** [primer/octicons#626]
The 24 size Sort icon is rendered differently compared to the 16 size variant:

<img width="454" alt="sort" src="https://user-images.githubusercontent.com/10718366/119867474-c7d58180-bed2-11eb-884f-03ce499f88dc.png">

### Steps to reproduce

- visit https://primer.style/octicons/sort-desc-24
- visit https://primer.style/octicons/sort-asc-24

**Comment by ashygee** [comment]
Thank you for noting this @metonym! Looking into it now

**Comment by metonym** [comment]
Just tested v14.2.1 and can confirm it's fixed.

Thank you – gorgeous library by the way.
