### ISSUE TITLE
How to build @primer/octicons-react@9.0.0

### ISSUE THREAD

**Issue by varunmankal** [primer/octicons#642]
I am trying to build and create NPM package of @primer/octicons-react@9.0.0 locally. I have cloned the repo and switched to 9.0.0 tag version of the code.

I ran the following steps to build it:
* npm install
* cd lib/octicons_react
* npm install
* npm run build

When I run `npm run build` it returns Error: Cannot find module '../../build/data.json' since there is no such file in the repo.

can I know how can I build this package locally ?

**Comment by colebemis** [comment]
You'll need to run the `build` script in the root directory as well:
```
npm install
npm run build
cd lib/octicons_react
npm install
npm run build
```
