### ISSUE TITLE
[Bug] Glyphs are no longer licensed

### ISSUE THREAD

**Issue by DHowett** [primer/octicons#645]
### Describe the bug
Commit a6fa69c9fab36dbec8bc2941e1d3f011f0989f88 removed SIL-OFL-1.1 from the license file, and commit 53efb185299aafd5895f3ae1c62d5058fbc126c2 removed it from the README. 
Commit 8fad660d18b8823039780319197a121479365662 was the last reference to SIL-OFL in the repository, which has been removed.

The README now only mentions the code, and the LICENSE only mentions the code.

We cannot assume that the glyphs are still available under the terms of the SIL OFL 1.1 license.

Can you please clarify the license on the glyphs?

**Comment by DHowett** [comment]
# Context

We would like to integrate the popular "Nerd Font" glyph set into [new monospaced font Cascadia Code](https://github.com/microsoft/cascadia-code) (as a downloadable variant.) This set of "nerd font" glyphs includes glyphs from Octicons. :smile:

**Comment by ashygee** [comment]
Hi @DHowett, apologies for such a long delay in response. Because we no longer support a font file so the removal of the SIL-OFL-1.1 license is correct. Octicons are available only in the form of code now as `<svg>`s and are covered by the MIT license.
