### ISSUE TITLE
Relocate icons to standardized code points where possible

### ISSUE THREAD

**Issue by Wuzzy2** [primer/octicons#68]
Most icons (in the font) reside in the Private Use Area but I have noticed that a lot of those icons could fit perfectly well into the “official” parts of Unicode. I.e. U+F02A (star icon) could be relocated to U+2605 BLACK STAR. Probably you will be surprised how many icons have actual Unicode code points.

Here's my proposed remapping list (some icons are mapped twice, this means I suggest do occupy both new codepoints) (please check the code point name; if there is some odd remapping, i.e. U+F000 (light bulb) on U+1F418 ELEPHANT, please complain because I probably made a mistake):

Old PUA, New standardized
F000, 1F4A1
F001, 1F4D1
F007, 1F46D
F00D,  2328
F011, 1F5B9
F012, 1F5BB
F013, 1F5DC
F015, 1F3F7
F016, 1F4C1
F016, 1F5BF
F018, 1F464
F02A,  2605
F02B, 1F4AC
F02D,  26A0
F02E, 1F50D
F02F,  26ED
F033, 1F680
F037, 1F465
F038, 1F4F1
F03A,  2713
F03B, 1F4E7
F03B, 1F582
F03D,  2191
F03E,  2192
F03F,  2193
F040,  2190
F041, 1F4CC
F043, 1F4CA
F044,  25C0
F045, 1F4B3
F046, 1F552
F049, 1F511
F04E, 1F441
F04F, 1F5EA
F052,  25CF
F053,  25A0
F056, 1F4F7
F057, 1F4F9
F058, 1F589
F059, 1F6C8
F05A,  25B2
F05B,  25BC
F05C, 1F517
F05D,    2B
F063,  275D
F065,  25E9
F068, 1F4C5
F069, 1F37A
F06A, 1F512
F06B,  229E
F06C,  229F
F06D,  22A1
F077, 1F56B
F07B, 1F516
F081,  274C
F084, 1F6AB
F087, 1F501
F088, 1F52D
F089, 1F52C
F08C, 1F575
F08D, 1F3E0
F091, 1F41B
F09E,  231B
F09E,  23F3
F09F, 1F839
F0A0, 1F83B
F0A1, 1F838
F0AA,  25B2
F0B6, 1F30E
F0BA, 1F50A
F0BB,  23F8
F0BC,  23EA
F0BD,  23E9
F0BE,    40
F0C4, 1F4E6
F0C5, 1F5D4
F0CA, 1F4E5
F0D0, 1F5D1
F0D2, 1F525
F0D3, 1F4BC
F0D4, 1F50C
F0D7, 1F393
F0D8,  2696
F0DA, 1F592
F0DB, 1F44E
F0DE, 1F514
F0E0,  231A
F27C, 1F5B5

Note: Icons without remapping just sta

**Comment by jonrohan** [comment]
We use the private use area on purpose and will probably not change that.
