### ISSUE TITLE
[Feedback] npm package contains duplicate icon data

### ISSUE THREAD

**Issue by xt0rted** [primer/octicons#699]
### Describe the topic

I just installed v16.1.1 of [@primer/octicons](https://www.npmjs.com/package/@primer/octicons) and noticed the `svg` folder and `data.json` file are duplicated in the package. I don't think this is intended and it's doubling the size of the package.

<img width="167" alt="image" src="https://user-images.githubusercontent.com/831974/142723128-d5176714-9a76-4470-a7c4-f34d1c78f4e9.png">

**Comment by ashygee** [comment]
Hi @xt0rted, thanks for letting us know! We'll take a look at this once we get some open bandwidth.

**Comment by xt0rted** [comment]
Still an issue in 17.2.0

**Comment by lesliecdubs** [comment]
@jonrohan is this something you might be able to squeeze in this quarter?

**Comment by tallys** [comment]
Following up, @jonrohan is this still an issue or can we close this?

**Comment by jonrohan** [comment]
I think this is still an issue. I believe both data sources are in use, so we'd need to investigate which one we can remove and update any libraries using them.

**Comment by tallys** [comment]
Hey @JoshBowdenConcepts, this might be a good one to pick up - thoughts?

**Comment by tallys** [comment]
Thank you for raising this issue, it is a known error and is in our backlog.

**Comment by fregante** [comment]
Would you accept a PR? Sounds like a quick change. This bug doubles the size of the package

https://packagephobia.com/result?p=@primer/octicons@13.0.0

**Comment by lesliecdubs** [comment]
Hi @fregante, thanks for the offer. Yes, we would gladly accept a PR for this change!

**Comment by fregante** [comment]
@lesliecdubs done

**Comment by lesliecdubs** [comment]
Thanks @fregante! ✨ We might be a little slower than usual with PR review due to the holiday season, but we should be able to get to it in the new year. Thanks for contibuting!

**Comment by fregante** [comment]
This can be closed once https://github.com/primer/octicons/pull/1010 is published to npm https://github.com/primer/octicons/commits/main/

**Comment by joshblack** [comment]
Just wanted to confirm that I don't see this anymore in v19.9.0. Going to close this out as I believe it's been addressed, feel free to leave a comment if I'm getting something wrong here!

**Comment by fregante** [comment]
Indeed in my link you can see the package going from 2.16 to 1.08, exactly half
