### ISSUE TITLE
[Bug] IssueOpenedIcon returns an incorrect icon

### ISSUE THREAD

**Issue by emilyyang-ms** [primer/octicons#707]
### Describe the bug
IssueOpenedIcon returns an incorrect icon in React project.

### Steps to reproduce
1. in my react project, I import the icon: `import {IssueOpenedIcon} from '@primer/octicons-react'`
2. render the icon
3. I see an incorrect icon rendered - a circle with ! in it.

### Expected behavior
IssueOpenedIcon should return correct icon. (a circle with dot in it) 
![image](https://user-images.githubusercontent.com/93799242/146069651-9cc21023-a125-4b29-aaaa-362ff1947f03.png)

### Screenshots
Here is the wrong icon screenshot:
![image](https://user-images.githubusercontent.com/93799242/146069066-bd7186ad-00b5-4904-8a16-103af1c9da91.png)

**Comment by colebemis** [comment]
👋  What version of `@primer/octicons-react` are you using?

**Comment by emilyyang-ms** [comment]
Hi Cole,

Thanks for checking, I installed this version
***@***.***/components": "^28.5.0",

Please let me know if anything is wrong with this version.

Thanks,
Emily

**Comment by colebemis** [comment]
The latest version of `@primer/react` (previously `@primer/component`) is [`34.0.0`](https://github.com/primer/react/releases). Upgrading should fix your issue.

If you don't want to update to the latest version of `@primer/react` yet. Try install the latest version of octicons explicitly:


```
npm install @primer/octicons-react@latest
```

**Comment by emilyyang-ms** [comment]
Thanks for the reply! I tried to update to latest @primer/react but it creates a bunch bugs(will deal with it later). For now I'll just update the lastest octicons and it works!

Thanks,
Emily

**Comment by emilyyang-ms** [comment]
Hi Cole,

I remember you mentioned the latest version of @primer/react has been changed, and we are still using the old library @primer/components 28.5.0. When I tried to update to the latest version, I figured out that the theming reference file has changed a lot, and some of the colors we were using are NOT in the new theming file now (like in old library, we can reference color auto.gray.1, but not in new library). So my questions are,


  1.  Do you suggest to upgrade to latest version of the library?
  2.  If we upgrade to latest version, what do you suggest to do with this theming reference change?

FYI, this project will be handed over to @Michael ***@***.***>

Thanks,
Emily

**Comment by 187880** [comment]
#[](rel=''prev'')
