### ISSUE TITLE
[Bug] Icon Request Link leads to 404

### ISSUE THREAD

**Issue by eagleEggs** [primer/octicons#716]
### Describe the bug
[Bug] Icon Request Link leads to 404 error

### Steps to reproduce
1. Go to [Icon Request Submission](https://github.com/github/primer/issues/new?assignees=ashygee&labels=octicon%2C+request&template=2-icon-request.md&title=%5BIcon+request%5D+)
2. See error

### Expected behavior
Icon submission page opens

**Comment by edokoa** [comment]
Hello, as noted under the new issue description, icon requests are only available for GitHub staff.

Sorry for the inconvenience.

![image](https://user-images.githubusercontent.com/694831/149144290-295e1949-2ca9-4a05-85af-67f53f881676.png)

**Comment by eagleEggs** [comment]
Aah ok. Didn't see that! Was hoping to request a keyboard icon, like WASD keys for instance. Thanks.
