### ISSUE TITLE
[Bug] Build fails due to dependency tree conflict with eslint-plugin-github@4.3.2 

### ISSUE THREAD

**Issue by Passeriform** [primer/octicons#775]
### Describe the bug
Required dependency `eslint-plugin-github@4.3.2` in turn has peer dependency for `eslint@^7.23.0` which conflicts with required dependency `eslint@8.0.1`. The install clears fine using npm but causes issues in dependency resolution when triggered by `yay`.

### Steps to reproduce
1. Install ttf-octicons from AUR: `yay -S ttf-octicons`
2. It runs `npm i @primer/octicons` which fails with the below error message

### Expected behavior
Installation should complete without an error.

### Device details

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.17.1-arch1-1
 - Node version: v16.14.2
 - Yay version: yay v11.1.2 - libalpm v13.0.1

### Additional info
**Error log:**
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @primer/octicons@17.0.0
npm ERR! Found: eslint@8.0.1
npm ERR! node_modules/eslint
npm ERR!   eslint@"8.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.23.0" from eslint-plugin-github@4.3.2
npm ERR! node_modules/eslint-plugin-github
npm ERR!   eslint-plugin-github@"4.3.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
Should be a simple update of eslint-github-plugin dependency to v

**Comment by colebemis** [comment]
Hi, @Passeriform! Thanks for the bug report ❤️  If you'd like to open a PR to bump our eslint-github-plugin dependency, I'd happy to review it :)

**Comment by Passeriform** [comment]
Hey @colebemis, sorry busy week. I've raised a PR for you to review #782  🙌

**Comment by colebemis** [comment]
Thanks for your patience! Will take a look today
