### ISSUE TITLE
[Feedback] react octicons should avoid`dangerouslySetInnerHtml`

### ISSUE THREAD

**Issue by mattcosta7** [primer/octicons#796]
### Describe the topic

When consuming in an environment that requires [trusted types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types)  these icons become unusable, since 'sinks' like innerHTML are limited to only consuming trusted types, every instance of an icons usage becomes an error

In order to support usage in more secure environments, moving these components to apis that utilize react children instead of 'dangerouslySetInnerHtml' is required. (Well, not necessarily required, as every icon could also accept a trusted type creator to wrap these calls to, or consumer one via context, but this would incur the performance hit of reading and running some trusted type creation on every render of the icon, where consuming children instead would not incur these penalties)

### Anything else?

I think there might be a low-overhead path to just pre-evaluating the 'path' html strings and writing them as jsx to be passed as children from svgHeightMaps at build time, but didn't have time to dig into it much 

https://github.com/primer/octicons/blob/6014f5d950653acc4fb670770721f695b40a4be5/lib/octicons_react/script/build.js#L20-L21

Something here where `JSON.stringify(octicon.heights)` becomes more like a 

```ts
JSON.strinfigy(Object.fromEntries(Object.entries(octicon.heights).map(([key, config]) => {
   const {path, ...restConfig} = config
   return [key, {...restConfig, children: convertToJsx(path)}
})))
```

and then `getSvgProps` is modified to return `children: children` instead of `dangerously....: path`

**Comment by brasic** [comment]
While we're changing how octicons work partly for performance reasons, would it make sense to consider adopting some of the ideas from https://github.com/github/primer/issues/424 (i.e. rendering a spritesheet and having individual octicons consist of just a `<us)? href="...">` call)?

**Comment by rezrah** [comment]
@lesliecdubs - how do you feel about bringing this into PRC planning?

**Comment by lesliecdubs** [comment]
@rezrah I'm open to that, but I'd first like to understand a bit more about the use case. 

@mattcosta7 can you tell us a bit more about where you're looking to use Octicons that requires trusted types? Is there a particular project or part of the product where this is needed on a particular timeline?

**Comment by mattcosta7** [comment]
> @rezrah I'm open to that as this seems like a reasonable suggestion, but I'd first like to understand a bit more about the use case.
> 
> @mattcosta7 can you tell us a bit more about where you're looking to use Octicons that requires trusted types? Is there a particular project or part of the product where this is needed on a particular timeline?


https://github.com/github/react-lang/issues/52 which came about from https://github.com/github/pse-architecture/issues/659 contain a good bit of information about the usecases

@kyfast might have a better idea on what timeline might look like for some of these, but since octicons are used internally in primer - there's a pretty firm dependency on octicons being updated to avoid dangerous html before any of that work could land

**Comment by lesliecdubs** [comment]
Thank you for the context, this is helpful!

I'm adding this to the Primer React inbox for further review.

**Comment by KyFaSt** [comment]
Thanks @mattcosta7 for looping me in here.

Hi @lesliecdubs trusted types is my team's next prioritized work but we want to work with frontend developers so that  may look like enabling the trusted types directive as report-only, or "allowlisting" these existing sinks until we can catch all of them. I'm afraid that's not really a definitive timeline, but does it help with your planning and work?

**Comment by lesliecdubs** [comment]
Thanks for the additional info, @KyFaSt! We'll take a look at sizing the effort of this change at our next team sync and get back to you.

**Comment by lesliecdubs** [comment]
@KyFaSt we reviewed this and were wondering if the changes seemed feasible for someone on your team to contribute and we'd be happy to review? Let us know how we can support you in this!
