### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by jayceeday** [primer/octicons#805]
hello, following up to our Octicon meeting today, I would like a recommendation on what Octicons I can use for badges.

### Badge Octicons
Here is the current selection (I removed ones we spoke about in the meeting)
<img width="979" alt="Screenshot 2022-07-20 at 10 23 59" src="https://user-images.githubusercontent.com/86061938/180044425-7259a59c-e7ae-480c-bf49-a56bd9edec08.png">

I would like to add megaphone, and if there are others that are fit!
 

You can also use this [Figma file](https://www.figma.com/file/HGe6eXeKmzm8iTwexsmoqp/badges-%2F-recognition?node-id=536%3A159830) and just leave here what I can use 

Natalya suggested that we follow the "Lucky Charms Rule" and just leave heart stars horseshoes clovers and balloons, and not GitHub UI. I'm not super sure what is used where so would be good to know what those Lucky Charms are. 

### Suggested Badges Icons
A question I forgot to ask is what I should do for our [5 suggested badges](https://www.figma.com/file/HGe6eXeKmzm8iTwexsmoqp/badges-%2F-recognition?node-id=536%3A159831)

This is what I currently have, but open to suggestions if you know of better ones! I'm really not set on the "Moderator" icon.
<img width="263" alt="Screenshot 2022-07-20 at 10 26 16" src="https://user-images.githubusercontent.com/86061938/180044893-95a2b256-62aa-425a-adf9-ad6b2a0478a1.png">

thank you all!

**Comment by jayceeday** [comment]
I spoke with Taryn as it was brought up a couple times that I should speak with her about branding

I messaged her and she said:

> Okay, cool. Fun feature! I don’t have any concerns about colors or icons, but agree that the :lower_left_paintbrush: Moderator one doesn’t feel quite right. What about [megaphone](https://primer.style/octicons/megaphone-24)?

**Comment by jayceeday** [comment]
Working session notes (From Ash):

> @jayceeday shared the upcoming user badge concepts that include colored label badges and octicons. The main question is around the set of icons to be allowed and @tallys made the suggestion for the "Lucky Charms" rule where we detach from any brand/product-related visuals and supply more generic options such as heart, sun, moon, bug, etc.

**Comment by edokoa** [comment]
I missed this session yesterday, but I’m reading the discussion now and my two cents more than not using UI specific icons is to not use icons with special meanings (ie: The north star icon, which is now reserved for Arctic Codevault), or not to use icons which don’t match the badge semantically (ie: The brush for moderation, which implies graphics/visual/design/art and was made for things such as themes, or color pickers).

I don’t have a problem myself with some of the badges like “rapid reviewer” using a flame, trusted responder using the speech bubbles, or core team using people, but I also see how those could be somehow refined, or if we have the resources, consider new metaphors we don’t have (for example a gavel / mallet for moderator), or a normal star or badge icon for “valued contributor”.

**Comment by edokoa** [comment]
On a secondary note, I feel like the 16px icons feel cramped inside of the labels (some of them touching the borders) and I'm also thinking about the small icons Julius made for timeline icons and if it would make sense to expand that set for those badges, unless we consider making the badges bigger, but that could also throw off the rest of the design.

**Comment by jayceeday** [comment]
thanks @edokoa !

I have changed the moderator icon to the megaphone based on taryn's suggestion. I don't think we have a perfect one for that yet, but is better than the paint brush <img width="208" alt="Screenshot 2022-07-21 at 11 52 54" src="https://user-images.githubusercontent.com/86061938/180293896-c8122a30-799b-4ca8-a0f4-d4fb76e35d8c.png">

Could you link me to the the project that Julius did that you are referring to and what size were the icons? 

I wanted to make the badges 22px high to make it more spacious but the maintainer badge we currently have is 20px high, we could update this but might increase scope. The 20px high also better fits in places, I can try with the smaller octicon and see how that feels!

**Comment by jayceeday** [comment]
I met with Jon Rohan in a Primer meeting, here are some points we spoke about: 

Once we have decided on the Octicons then we can try out the smaller icons with the badge, and hopefully the Octicons team can give feedback. 

These were the options:

<img width="540" alt="Screenshot 2022-07-21 at 16 02 32" src="https://user-images.githubusercontent.com/86061938/180329215-088f358c-985b-4118-99f3-b37bfb7d4021.png">

I think we have to keep the 18px line height + 1px border (top and bottom, so 20px, because that is what we use everywhere else for labels. Jon said it'd be a bigger lift to make the padding larger, so should try with the smaller icons. 

Here is for the suggested labels, do the octicons look too small? Or is this better than my previous screenshot?
<img width="773" alt="Screenshot 2022-07-21 at 16 09 17" src="https://user-images.githubusercontent.com/86061938/180329744-5892e020-cb27-4bd9-ac23-7abf8336c167.png">

**Comment by ashygee** [comment]
@jayceeday I'm not sure how I feel about resizing the octicons as our [usage guidelines](https://primer.style/octicons/guidelines/usage#sizing) state that the icons should be used at their intended size of 16px or 24px. I'm happy to work with you on how we can find a good solution together though. As @edokoa mentioned this could be an instance where we expand the sizing for the 12px icons which is the same size as the feed icons created by @Juliusschaeper.

As far as the icon set goes, I would remove the followingf icons:

- [code-scan icon](https://primer.style/octicons/codescan-16) which is the search with <> as that is specifically used for security code scanning.
- asterisk/[north-star icon](https://primer.style/octicons/north-star-16) used for Arctic Code Vault, you could replace with the regular [star icon](https://primer.style/octicons/star-16)

The rest of the set feels pretty generic which I feel works.

**Comment by edokoa** [comment]
Just chiming in to +1 @ashygee: Octicons should never be resized, that's why I was proposing expanding the 12px set.

**Comment by jayceeday** [comment]
Thank you @ashygee + @edokoa !

When I mentioned the different sizing, I was referring to expanding the 12px set by Julius, not an entirely new size. 

Here is an example of using the 16px vs. expanding Julius' 12px set. Would love your feedback of which one you think looks better, and if I can expand the set? I think I like the 12px ones. 
<img width="1049" alt="Screenshot 2022-08-01 at 12 01 17" src="https://user-images.githubusercontent.com/86061938/182124686-54ca4d43-57d7-415b-84b4-2584af74e70c.png">

Also for the icon set I'd love to use the trophy, ruby and certified. Not sure exactly where else in GH they are used. Could I replace some with these? Maybe the certified is already saved for something similar.

<img width="45" alt="Screenshot 2022-08-01 at 11 55 46" src="https://user-images.githubusercontent.com/86061938/182144484-b7ca7ff0-d4ef-467c-8574-1d9887978804.png"><img width="39" alt="Screenshot 2022-08-01 at 11 56 10" src="https://user-images.githubusercontent.com/86061938/182144488-5dbcca87-328b-40aa-86c0-34a2ec9f1af5.png"><img width="37" alt="Screenshot 2022-08-01 at 11 56 28" src="https://user-images.githubusercontent.com/86061938/182144491-a55ed92f-338f-496f-aae3-81d3086f2885.png">

**Comment by jayceeday** [comment]
Moved to our private repo https://github.com/github/primer/issues/1188
