### ISSUE TITLE
[Feedback] Improve stale action used

### ISSUE THREAD

**Issue by Andre601** [primer/octicons#808]
### Describe the topic

This is related to the Stale action used within this repository.

While I can see the benefits of keeping the issue tracker clean and up to date, is it not really good if someone opens a bug report, only to not get any reply within 180 days and then have their issue marked as stale.

Marking it as stale does obviously not have that much of an impact at first. But it does require the creator to make an arbitrary action, which is writing a comment that the issue is still present.

Instead of this basic setup should the action only react if the issue has been replied to by a maintainer or assigned person. The easiest way for this would be to look for a label assigned to the issue to then mark as stale if no reply/action has been made towards the issue while having this label.
F.e. a "Waiting for reply" label would suit this use-case here.

That way would only issues that are truly inactive be marked as stale while those waiting for a response from the right people are unaffected.

### Anything else?

As mentioned is this not a big deal. After all is it only *marking* it as stale, which can be reverted with a simple comment.
But having to write a comment just for this feels pointless for the issue creator who has to wait for an actual reply.

**Comment by tallys** [comment]
Hi @Andre601 thanks for your patience on this. The assignees that were listed on this issue by ashygee are not actively working on the Octicons group. I'm taking over managing the Octicons group. Will be addressing the reply issues.
