### ISSUE TITLE
[Bug] repo-pull has incorrect border width

### ISSUE THREAD

**Issue by thien-do** [primer/octicons#814]
### Describe the bug

Repo pull icon has 1px width, not 1.5:

<img width="148" alt="image" src="https://user-images.githubusercontent.com/5953369/183237497-a9e638e9-1f1f-4ff4-87b8-cdbe89764cbd.png">

### Steps to reproduce

https://primer.style/octicons/repo-pull-16

**Comment by ashygee** [comment]
@thien-do thanks for this issue. The repo-pull icon needs to be redrawn to follow our [design guidelines](https://primer.style/octicons/guidelines/design) so we will add this to our backlog.

**Comment by Daeraxa** [comment]
Just to add to this `repo-clone` (https://primer.style/design/foundations/icons/repo-clone-16) seems to also be using the older style

**Comment by Ninja-mann07** [comment]
ok

**Comment by gavinmn** [comment]
I believe this PR should have addressed this issue https://github.com/primer/octicons/pull/970
