### ISSUE TITLE
[Icon request] Poweroff

### ISSUE THREAD

**Issue by thisconnect** [primer/octicons#844]
### Describe the topic

Could you add a turnoff / poweroff icon? Often it is a circle with a line in the middle.

### Anything else?

Thank you for this pretty icon set

**Comment by tallys** [comment]
Closing out old issues in this repo. 

If this is still a request, please open an [icon review issue](https://github.com/github/primer/issues/new?assignees=&labels=octicon%2C+request%2C+needs+triage&template=02-icon-request.md&title=%5BIcon+request%5D+) in the [GitHub Primer repo](https://github.com/github/primer#need-a-pattern-or-octicon-)

**Comment by thisconnect** [comment]
hello @tallys unfortunately the links you provided 404
