### ISSUE TITLE
[Icon request] Save icon

### ISSUE THREAD

**Issue by thisconnect** [primer/octicons#845]
### Describe the topic

Could not find a save icon, as there is edit and delete it would also be nice to have save icon usually it's styled like a floppy disk.

**Comment by ashygee** [comment]
Hi @thisconnect, thanks for requesting this. I am going to add this to our backlog to discuss but in the meantime we do have the [download](https://primer.style/octicons/download-16) and [desktop-download](https://primer.style/octicons/desktop-download-16) icons that might be able to help depending on how the saving function works.
