### ISSUE TITLE
Update React components to use `React.forwardRef()`

### ISSUE THREAD

**Issue by joshblack** [primer/octicons#910]
Currently our Icon components are exported as plain functional components. It would be great if we included support for forwarding refs through `React.forwardRef()`, however this is only available past [React v16.3](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#forwardref-api). Currently, the project lists React v15 as a peer dependency.

It seems like we have a couple of paths forward:

- Increase the peer dependency range, but still include v15, and try and feature detect `forwardRef`. This would land in a `minor` change to the package
- Increase the peer dependency range explicitly to >=v16.3 and unconditionally use `forwardRef`. This would land in a `major` change to the package

**Comment by lesliecdubs** [comment]
Open question that came up at PRC maintainer's sync: is there any issue with releasing thsi major change we would need to account for?

@colebemis has the most context on this repo and said it's a pretty safe breaking change to go ahead and make, but feel free to coordinate directly as needed.
