### ISSUE TITLE
Icon is not Centered

### ISSUE THREAD

**Issue by Neodevils** [primer/octicons#915]
> North Star icon is not centered.

![image](https://user-images.githubusercontent.com/71941576/216816576-9b74d74b-bcdc-47b9-b2d5-7f045b08902d.png)

**Comment by tallys** [comment]
Hey! Thanks for opening the issue - I'll forward it to the team.

**Comment by gavinmn** [comment]
Is this misalignment causing an issue? I didn't create the icon but I'm guessing it was done this way so that the vertical and horizontal lines are properly aligned to the pixel grid. Directly centering it would cause all lines to be set on half or quarter pixels.

**Comment by Neodevils** [comment]
> Is this misalignment causing an issue? I didn't create the icon but I'm guessing it was done this way so that the vertical and horizontal lines are properly aligned to the pixel grid. Directly centering it would cause all lines to be set on half or quarter pixels.

Well, yes. Misalignment. Either the vector has to be a little bit longer or shorter then.

**Comment by gavinmn** [comment]
I did some more tests with this icon in the UI and feel like the half pixel alignment on the vertical and horizontal lines is probably worth the trade off. I'll see about getting this change shipped in the next update.

**Comment by Neodevils** [comment]
> I did some more tests with this icon in the UI and feel like the half pixel alignment on the vertical and horizontal lines is probably worth the trade off. I'll see about getting this change shipped in the next update.

Thank you. I'll be watching this issue.

**Comment by tallys** [comment]
Hi, thanks for bringing this up and thanks for the due diligence @gavinmn. I'm chiming in with some history on the creation of this icon, there was a specific reason that we decided to make it slightly off centered, so we will not be shifting it at this time.
