### ISSUE TITLE
[Docs] Missing guidelines for 12px icons

### ISSUE THREAD

**Issue by lukasoppermann** [primer/octicons#936]
I am in need of a 12px icon I want to contribute and noticed that the guidelines only specify how to create 16px and 24px icons: https://primer.style/design/foundations/icons/design-guidelines

It would be great if 12px guidelines could be included as well.

**Comment by tallys** [comment]
Hey @lukasoppermann the 12px icons were an exception, and we are only supporting 16px and 24px sizes. If this is for a specific icon for a product, fill out an [issue template](https://github.com/github/primer/issues/new?assignees=&labels=octicon%2C+request%2C+needs+triage&template=03-icon-request.md&title=%5BIcon+request%5D+) and we can work through it in an upcoming working session.

**Comment by lukasoppermann** [comment]
> Hey @lukasoppermann the 12px icons were an exception, and we are only supporting 16px and 24px sizes.

Makes sense, but two points:
1. Shouldn't we mention exactly this somewhere? As the first thing you see on the overview page are [the 12px icons](https://primer.style/design/foundations/icons)
2. I needed a product specific 12px icon, so wouldn't it still be good to know how to design it if needed?

> If this is for a specific icon for a product, fill out an [issue template](https://github.com/github/primer/issues/new?assignees=&labels=octicon%2C+request%2C+needs+triage&template=03-icon-request.md&title=%5BIcon+request%5D+) and we can work through it in an upcoming working session.

I did this any way (https://github.com/github/primer/issues/1965) and have added the icon to figma via a PR.
