### ISSUE TITLE
[Icon Request] Empty Checkbox

### ISSUE THREAD

**Issue by yardenshoham** [primer/octicons#942]
To show a button for adding an empty checkbox I'd like an icon exactly like https://primer.style/design/foundations/icons/checkbox-16 but without the checkmark. That way I'd have an SVG for both an empty checkbox and a checked checkbox.

How about:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M2.75 1h10.5c.966 0 1.75.784 1.75 1.75v10.5A1.75 1.75 0 0 1 13.25 15H2.75A1.75 1.75 0 0 1 1 13.25V2.75C1 1.784 1.784 1 2.75 1ZM2.5 2.75v10.5c0 .138.112.25.25.25h10.5a.25.25 0 0 0 .25-.25V2.75a.25.25 0 0 0-.25-.25H2.75a.25.25 0 0 0-.25.25Z"/></svg>
```

**Comment by tallys** [comment]
Hi, thanks for opening the issue. We already have a [Square Icon](https://primer.style/design/foundations/icons/square-24) in Octicons.

**Comment by yardenshoham** [comment]
Next to the checkbox, it looks like they have different sizes

**Comment by tallys** [comment]
Hi @yardenshoham, we intentionally do not have an empty toggle checkbox. Additionally, including it could potentially encourage inaccessible checkboxes in being built in the UI. If you need a checkbox, check out https://primer.style/react/Checkbox.
