### ISSUE TITLE
[Bug] `@primer/octicons-react` v19.0.0 not published

### ISSUE THREAD

**Issue by silverwind** [primer/octicons#946]
### Describe the bug
v19.0.0 was released but not published to npm.

### Steps to reproduce
https://github.com/primer/octicons/actions/runs/4919743480/jobs/8787754759

### Expected behavior
Release to appear on https://www.npmjs.com/package/@primer/octicons

**Comment by broccolinisoup** [comment]
Hi! @silverwind 👋🏻 Thanks for raising this issue! We are looking into it 👀 and will update here once we are able to publish it!

**Comment by broccolinisoup** [comment]
We managed to resolve the issues and publish the octicons 🎉 v19.0.1 is available on NPM https://www.npmjs.com/package/@primer/octicons-react
