### ISSUE TITLE
[Feedback] No empty/unchecked checkbox to go with "checkbox" icon?

### ISSUE THREAD

**Issue by rahji** [primer/octicons#955]
### Describe the topic

There is a "checkbox" icon, but no corresponding unchecked box icon.

**Comment by tallys** [comment]
Hi @rahji, thanks for opening the issue. The icons are intended to be visual language to enhance UI, bot not interactive.
The Octicons set has the square icon, but we intentionally choose not have an empty toggle checkbox. Including it could potentially encourage inaccessible checkboxes being built in the UI. If you need a checkbox, see https://primer.style/react/Checkbox.

**Comment by rahji** [comment]
That makes sense. I think the actual use case that I have matches up with what you're saying actually. The Todo Tree vscode extension uses Octicons as indicators in the gutter (not interactive at all). It's nice to be able to indicate both comments that are yet to be done and those that are completed. I'm using other icons instead, but empty and checked boxes would have been ideal for this situation. In any case, thanks for the reply.
