### ISSUE TITLE
[Feedback] Repo Icons are inconsistent

### ISSUE THREAD

**Issue by silverwind** [primer/octicons#965]
### Describe the topic

The `repo-*` icons are not consistent with themselves:

16px:
<img width="926" alt="image" src="https://github.com/primer/octicons/assets/115237/ca6dac4b-78ea-445c-aea8-86495600204d">
24px:
<img width="666" alt="image" src="https://github.com/primer/octicons/assets/115237/bf275b16-7eeb-4d9c-b78e-441d2f815c44">

- The 16px and 24px `repo-forked` bear no resemblance to the others. It could use a similar style as the others with the fork icon on bottom right.
- The 16px `repo-pull` and `repo-clone` seem to be using the old version of the `repo` icon. Suggesting to update to new version.

**Comment by tallys** [comment]
Hi @silverwind - thanks for opening the issue. We've discussed this in our Octicons working group and will be adding these updates to our roadmap.

**Comment by CameronFoxly** [comment]
These have all been updated, and are currently live at [primer.style](https://primer.style/design/foundations/icons).  Closing this out. 

Thanks for flagging!
