### ISSUE TITLE
[Bug] Discrepancies Between Figma Octicons Set and React Library

### ISSUE THREAD

**Issue by JonathanXDR** [primer/octicons#973]
### Describe the bug
The Figma community page for the Octicons icon set seems to be outdated, leading to discrepancies between the icons (including their different sizes) available in the Figma set and the current Primer Octicons library. E.g. the Paintbrush Octicon with a size of 24px, present in the Figma set, is absent in the React library.

### Steps to reproduce
1. Go to the official Figma community page for Octicons: [Octicons - GitHub's icon set (Community)](https://www.figma.com/community/file/809920999413919915/Octicons---GitHub's-icon-set)
2. Observe the set of icons available, especially the Paintbrush icon with a size of 24px.
3. Compare the Figma set with the [React library](https://primer.style/design/foundations/icons).
4. Notice the absence of some icons, like the Paintbrush, in the React library.

### Expected behavior
The Figma set and the React library should be in sync, with the same set of icons & sizes available in both. If there are icons present in the Figma set that are not in the library (or vice versa), this should be clearly documented.

#### Octicon overview in Figma
<img width="300" alt="octicon overview in figma" src="https://github.com/primer/octicons/assets/73559516/4e17b85e-8e1e-4fc1-b692-fb98b84e3d93">

#### Octicon overview in the Primer documentation
<img width="910" alt="octicon overview in the primer documentation" src="https://github.com/primer/octicons/assets/73559516/97bdd7be-01e1-4b92-a439-ea15b8542f2c">

### Device details

**Desktop:**
 - OS: macOS Sonoma
 - Browser: Arc
 - Version: 1.3.0 (40706)
 - Chromium Engine Version: 115.0.5790.170

### Additional info
The attached screenshots can be referenced for the current set of icons in Figma & the React library. It would be beneficial for developers and designers to have a consistent set of icons across all platforms and documentation.

**Comment by tallys** [comment]
@JonathanXDR thanks for opening the issue - sending it to the Octicon working group inbox

**Comment by JonathanXDR** [comment]
@tallys and @lukasoppermann, could we reopen the issue until all reviewers of #983 have approved and the PR was merged?
