### ISSUE TITLE
[Feedback] Duplicated icons

### ISSUE THREAD

**Issue by lukasoppermann** [primer/octicons#984]
Some icons exist with multiple names twice.

### Describe the topic

For example, we have the icons `image` and `file-media` which is the same icon. Or `tab` and `move-to-end`.

Is this desired or an issue we should fix?

**Comment by silverwind** [comment]
Imho, remove duplicates and push a major release afterwards.

**Comment by tallys** [comment]
If we remove it, it will break, so this is a will-not-fix
