### ISSUE TITLE
[Suggestion] Add `git-branch-deleted` and `tag-deleted` icons

### ISSUE THREAD

**Issue by delvh** [primer/octicons#989]
### Description

At the moment, there is no visual distinction between when a branch was created and when it is deleted again as both need to share the same icon, `git-branch`.
The same applies to tags/releases with the `tag` icon.
If there were a `deletion` icon for either, users would not need to skim through the text of a timeline entry to find out if this entry means that the branch/tag/release was added or deleted.
Furthermore, it could be used in a UI at the places that actually offer the deletion functionality, for example as a `confirm action` icon.

Regarding the design, my intuitive guess would be something like the existing icon with a `×` or something like that in the bottom right corner.

**Comment by tallys** [comment]
Thanks for opening the issue, I'll add this for discussion for the Octicons working group.

**Comment by delvh** [comment]
I guess this means it was discussed and then discarded?
