### ISSUE TITLE
[Bug] `@primer/octicons-react` includes raw SVG files, but are inaccessible

### ISSUE THREAD

**Issue by fregante** [primer/octicons#998]
### Describe the bug

The `@primer/octicons-react` package includes the raw SVGs:

https://www.unpkg.com/browse/@primer/octicons-react@19.8.0/build/

but they're not accessible because `exports` map blocks its access:

https://github.com/primer/octicons/blob/6bc78de32be1a218a69e10a731072331ba94e7f9/lib/octicons_react/package.json#L10-L14

### Expected behavior

I don’t think they're useful in this package, so they should probably just be removed.

**Comment by joshblack** [comment]
I believe this was closed by #1009, sorry again about my mistake with merging @fregante!
